### ISSUE TITLE
"export the model by script failed"

### ISSUE THREAD

**Issue by Maggione** [wenet-e2e/wenet#1033]
**Describe the bug**
I try to run the standard transformer on the aishell-1 dataset.  I use the script "wenet-main/examples/aishell/s0/run.sh" and got the error like this:
```
Traceback (most recent call last):
  File "wenet/bin/train.py", line 296, in <module>
    main()
  File "wenet/bin/train.py", line 204, in main
    script_model = torch.jit.script(model)
  File "~/miniconda3/envs/mm-fairseq2/lib/python3.6/site-packages/torch/jit/_script.py", line 898, in script
    obj, torch.jit._recursive.infer_methods_to_compile
  File "~/miniconda3/envs/mm-fairseq2/lib/python3.6/site-packages/torch/jit/_recursive.py", line 352, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "~/miniconda3/envs/mm-fairseq2/lib/python3.6/site-packages/torch/jit/_recursive.py", line 406, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "~/miniconda3/envs/mm-fairseq2/lib/python3.6/site-packages/torch/jit/_script.py", line 388, in _construct
    init_fn(script_module)
  File "~/miniconda3/envs/mm-fairseq2/lib/python3.6/site-packages/torch/jit/_recursive.py", line 388, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "~/miniconda3/envs/mm-fairseq2/lib/python3.6/site-packages/torch/jit/_recursive.py", line 406, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "~/miniconda3/envs/mm-fairseq2/lib/python3.6/site-packages/torch/jit/_script.py", line 388, in _construct
    init_fn(script_module)
  File "~/miniconda3/envs/mm-fairseq2/lib/python3.6/site-packages/torch/jit/_recursive.py", line 388, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "~/miniconda3/envs/mm-fairseq2/lib/python3.6/site-packages/torch/jit/_recursive.py", line 406, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "~/miniconda3/envs/mm-fairseq2/lib/python3.6/site-packages/torch/jit/_script.py", line 388, in _construct
    init_fn(script_module)
  File "~/miniconda3/envs/mm-fairseq2/lib/python3.6/site-packages/torch/jit/_recursive.py", line 388, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, stubs_fn)
  File "~/miniconda3/envs/mm-fairseq2/lib/python3.6/site-packages/torch/jit/_recursive.py", line 410, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "~/miniconda3/envs/mm-fairseq2/lib/python3.6/site-packages/torch/jit/_recursive.py", line 304, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
  File "~/miniconda3/envs/mm-fairseq2/lib/python3.6/site-packages/torch/jit/annotations.py", line 279, in try_ann_to_type
    return TupleType([try_ann_to_type(a, loc) for a in ann.__args__])
RuntimeError: Can not create tuple with None type
```
The code notes that 
```
    # !!!IMPORTANT!!!
    # Try to export the model by script, if fails, we should refine
    # the code to satisfy the script export requirements
```
What does the error mean? How can I fix it? 

**To Reproduce**
sh wenet-main/examples/aishell/s0/run.sh

**Desktop (please complete the following information):**
 - OS: Linux
 - pytorch: 1.7.0_gpu
 - python: 3.6

**Comment by xiangxyq** [comment]
hi Maggione,
Could you try to use pytorch 1.10.0 and python3.8 as readme said, https://github.com/wenet-e2e/wenet/blob/main/README.md#installation

**Comment by xingchensong** [comment]
fixed, https://github.com/wenet-e2e/wenet/pull/1037
