### ISSUE TITLE
onnx GPU streaming export failed

### ISSUE THREAD

**Issue by Nucleus17** [wenet-e2e/wenet#1197]
**branch main commit  e1132d58afd8c9b899** 

onnx gpu streaming failed

```
cd examples/aishell2/s0 && . ./path.sh

wget https://wenet-1256283475.cos.ap-shanghai.myqcloud.com/models/aishell/20211025_conformer_exp.tar.gz
tar -xf 20211025_conformer_exp.tar.gz
model_dir=20211025_conformer_exp
onnx_model_dir=${model_dir}/onnx_gpu
mkdir $onnx_model_dir

python3 wenet/bin/export_onnx_gpu.py --config=$model_dir/train.yaml --checkpoint=$model_dir/final.pt --cmvn_file=$model_dir/global_cmvn  --ctc_weight=0.1 --reverse_weight=0.4 --output_onnx_dir=$onnx_model_dir --fp16 --streaming
cp $model_dir/words.txt $model_dir/train.yaml $onnx_model_dir/
```

error

```
Traceback (most recent call last):
  File "wenet/bin/export_onnx_gpu.py", line 574, in <module>
    onnx_config = export_enc_func(model, configs, args, logger, encoder_onnx_path)
  File "wenet/bin/export_onnx_gpu.py", line 418, in export_online_encoder
    ort_outs = ort_session.run(None, ort_inputs)
  File "wenet/venv/lib/python3.6/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 192, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid Feed Input Name:cnn_cache
```

**Comment by Nucleus17** [comment]
can you update the README https://github.com/wenet-e2e/wenet/tree/main/runtime/server/x86_gpu, make it clear.

**Comment by Slyne** [comment]
The updated [README for pretrained models](https://github.com/wenet-e2e/wenet/blob/main/docs/pretrained_models.md) on main branch only has pretrained models of u2/u2++.  

Just in case users don't understand what a streaming model is, I add a notice:
https://github.com/wenet-e2e/wenet/pull/1201

Feel free to reopen this issue.

**Comment by ZOKIEN** [comment]
so if I only use train_conformer.yaml  train a model,  I cant export it into onnx-gpu?
