### ISSUE TITLE
Exec export_onnx_cpu.py error 

### ISSUE THREAD

**Issue by Zepan** [wenet-e2e/wenet#1209]
get error when use export_onnx_cpu.py to export wenet pretrain model (20220506_u2pp_conformer_exp)
python3 wenet/bin/export_onnx_cpu.py  \
    --config wenet_mdl/20220506_u2pp_conformer_exp/train.yaml \
    --checkpoint wenet_mdl/20220506_u2pp_conformer_exp/final.pt \
    --output_dir wenet_mdl/20220506_u2pp_conformer_exp/ \
    --chunk_size 16 \
    --num_decoding_left_chunks 4 \
    --reverse_weight 0.5

```
(pytorch_gpu) bits@sipeed-ai:~/workspace/opensource/wenet$ python3 wenet/bin/export_onnx_cpu.py      --config wenet_mdl/20220506_u2pp_conformer_exp/train.yaml     --checkpoint wenet_mdl/20220506_u2pp_conformer_exp/final.pt     --output_dir wenet_mdl/20220506_u2pp_conformer_exp/     --chunk_size 16     --num_decoding_left_chunks 16     --reverse_weight 0.5
ASRModel(
   ...
  )
  (ctc): CTC(
    (ctc_lo): Linear(in_features=512, out_features=5538, bias=True)
    (ctc_loss): CTCLoss()
  )
  (criterion_att): LabelSmoothingLoss(
    (criterion): KLDivLoss()
  )
)
Stage-1: export encoder
	Stage-1.1: prepare inputs for encoder
		chunk.size(): torch.Size([1, 67, 80])
 		offset: 256
 		required_cache: 256
 		att_cache.size(): torch.Size([12, 8, 256, 128])
 		cnn_cache.size(): torch.Size([12, 1, 512, 14])
 		att_mask.size(): torch.Size([1, 1, 272])

	Stage-1.2: torch.onnx.export
/home/bits/workspace/opensource/wenet/wenet/transformer/encoder.py:220: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert xs.size(0) == 1
/home/bits/workspace/opensource/wenet/wenet/transformer/embedding.py:99: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert offset + size < self.max_len
/home/bits/workspace/opensource/wenet/wenet/transformer/encoder.py:237: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if required_cache_size < 0:
/home/bits/workspace/opensource/wenet/wenet/transformer/encoder.py:239: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  elif required_cache_size == 0:
/home/bits/workspace/opensource/wenet/wenet/transformer/encoder.py:242: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  next_cache_start = max(attention_key_size - required_cache_size, 0)
/home/bits/workspace/opensource/wenet/wenet/transformer/encoder.py:251: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  att_cache=att_cache[i:i + 1] if elayers > 0 else att_cache,
/home/bits/workspace/opensource/wenet/wenet/transformer/encoder.py:252: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  cnn_cache=cnn_cache[i] if cnn_cache.size(0) > 0 else cnn_cache
/home/bits/workspace/opensource/wenet/wenet/transformer/attention.py:278: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if cache.size(0) > 0:
/home/bits/anaconda3/envs/pytorch_gpu/lib/python3.7/site-packages/torch/_tensor.py:575: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  ../aten/src/ATen/native/BinaryOps.cpp:467.)
  return torch.floor_divide(self, other)
/home/bits/workspace/opensource/wenet/wenet/transformer/attention.py:101: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if mask.size(2) > 0 :  # time2 > 0
/home/bits/workspace/opensource/wenet/wenet/transformer/convolution.py:112: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if mask_pad.size(2) > 0:  # time > 0
/home/bits/workspace/opensource/wenet/wenet/transformer/convolution.py:116: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if cache.size(2) == 0:  # cache_t == 0
/home/bits/workspace/opensource/wenet/wenet/transformer/convolution.py:119: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert cache.size(0) == x.size(0)  # equal batch
/home/bits/workspace/opensource/wenet/wenet/transformer/convolution.py:120: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert cache.size(1) == x.size(1)  # equal channel
/home/bits/workspace/opensource/wenet/wenet/transformer/convolution.py:122: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert (x.size(2) > self.lorder)
/home/bits/workspace/opensource/wenet/wenet/transformer/convolution.py:143: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if mask_pad.size(2) > 0:  # time > 0
Traceback (most recent call last):
  File "wenet/bin/export_onnx_cpu.py", line 399, in <module>
    main()
  File "wenet/bin/export_onnx_cpu.py", line 393, in main
    export_encoder(model, arguments)
  File "wenet/bin/export_onnx_cpu.py", line 161, in export_encoder
    dynamic_axes=dynamic_axes, verbose=False)
  File "/home/bits/anaconda3/envs/pytorch_gpu/lib/python3.7/site-packages/torch/onnx/__init__.py", line 280, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/bits/anaconda3/envs/pytorch_gpu/lib/python3.7/site-packages/torch/onnx/utils.py", line 94, in export
    use_external_data_format=use_external_data_format)
  File "/home/bits/anaconda3/envs/pytorch_gpu/lib/python3.7/site-packages/torch/onnx/utils.py", line 695, in _export
    dynamic_axes=dynamic_axes)
  File "/home/bits/anaconda3/envs/pytorch_gpu/lib/python3.7/site-packages/torch/onnx/utils.py", line 467, in _model_to_graph
    module=module)
  File "/home/bits/anaconda3/envs/pytorch_gpu/lib/python3.7/site-packages/torch/onnx/utils.py", line 200, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/bits/anaconda3/envs/pytorch_gpu/lib/python3.7/site-packages/torch/onnx/__init__.py", line 313, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/bits/anaconda3/envs/pytorch_gpu/lib/python3.7/site-packages/torch/onnx/utils.py", line 994, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/home/bits/anaconda3/envs/pytorch_gpu/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py", line 172, in wrapper
    return fn(g, *args, **kwargs)
  File "/home/bits/anaconda3/envs/pytorch_gpu/lib/python3.7/site-packages/torch/onnx/symbolic_opset13.py", line 73, in split
    if self.type().sizes()[dim] is not None:
TypeError: 'NoneType' object is not subscriptable 
(Occurred when translating split).

```

**Comment by robin1001** [comment]
@xingchensong , please follow the issue.

**Comment by groovemaxRong** [comment]
Also having this error in the last code.
```
...
if self.type().sizes()[dim] is not None:
TypeError: 'NoneType' object is not subscriptable
(Occurred when translating split)
```

**Comment by pengaoao** [comment]
我这边也碰到同样的问题了。

**Comment by TinaChen95** [comment]
Same question. Can anyone who success in executing export_onnx_cpu.py share pytorch, onnx and onnxruntime version?

遇到相同的问题。是否有成功export的朋友分享一下pythorch，onnx和 onnxruntime的版本呢？

**Comment by xingchensong** [comment]
I will follow up on this issue

**Comment by xingchensong** [comment]
I cannot reproduce this issue:
![211b10f9c6d8c0350bca3b2552ed852](https://user-images.githubusercontent.com/13466943/190969411-03ad1314-a1b7-49d1-8d56-d93bc374e12a.jpg)

My env:
```sh
python 3.8.12
torch 1.10.0
onnx 1.11.0
onnxruntime 1.11.0
```

**Comment by TinaChen95** [comment]
I reproduce this issue under torch 1.10.0 + onnx 1.12.0 + onnxruntim 1.12.1
But when I upgrade torch to 1.12.0, this issue disapeared.
