### ISSUE TITLE
libtorch gpu解码错误

### ISSUE THREAD

**Issue by v-yunbin** [wenet-e2e/wenet#1346]
```
Traceback (most recent call last):
  File "test_text_e2e_wenet.py", line 9, in <module>
    decoder = wenet.Decoder(lang='chs',model_dir="/home/ybZhang/.wenet/chs/wenetspeech")
  File "/home/ybZhang/miniconda3/envs/wenet/lib/python3.8/site-packages/wenet/decoder.py", line 45, in __init__
    self.d = _wenet.wenet_init(model_dir)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/torch/nn/quantized/modules/linear.py", line 18, in __setstate__
    state: Tuple[Tensor, Optional[Tensor], bool, int]) -> NoneType:
    self.dtype = (state)[3]
    _1 = (self).set_weight_bias((state)[0], (state)[1], )
          ~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    self.training = (state)[2]
    return None
  File "code/__torch__/torch/nn/quantized/modules/linear.py", line 41, in set_weight_bias
    _10 = "Unsupported dtype on dynamic quantized linear!"
    if torch.eq(self.dtype, 12):
      _11 = ops.quantized.linear_prepack(weight, bias)
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
      self._packed_params = _11
    else:

Traceback of TorchScript, original code (most recent call last):
  File "/home/binbzha/miniconda3/envs/wenet/lib/python3.8/site-packages/torch/nn/quantized/modules/linear.py", line 94, in __setstate__
    def __setstate__(self, state):
        self.dtype = state[3]
        self.set_weight_bias(state[0], state[1])
        ~~~~~~~~~~~~~~~~~~~~ <--- HERE
        self.training = state[2]
  File "/home/binbzha/miniconda3/envs/wenet/lib/python3.8/site-packages/torch/nn/quantized/modules/linear.py", line 24, in set_weight_bias
    def set_weight_bias(self, weight: torch.Tensor, bias: Optional[torch.Tensor]) -> None:
        if self.dtype == torch.qint8:
            self._packed_params = torch.ops.quantized.linear_prepack(weight, bias)
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        elif self.dtype == torch.float16:
            self._packed_params = torch.ops.quantized.linear_prepack_fp16(weight, bias)
RuntimeError: Could not run 'quantized::linear_prepack' with arguments from the 'QuantizedCUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'quantized::linear_prepack' is only available for these backends: [QuantizedCPU, BackendSelect, Python, Named, Conjugate, Negative, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradLazy, AutogradXPU, AutogradMLC, Tracer, UNKNOWN_TENSOR_TYPE_ID, Autocast, Batched, VmapMode].

QuantizedCPU: registered at ../aten/src/ATen/native/quantized/cpu/qlinear_prepack.cpp:324 [kernel]
BackendSelect: fallthrough registered at ../aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Python: registered at ../aten/src/ATen/core/PythonFallbackKernel.cpp:47 [backend fallback]
Named: registered at ../aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
Conjugate: registered at ../aten/src/ATen/ConjugateFallback.cpp:18 [backend fallback]
Negative: registered at ../aten/src/ATen/native/NegateFallback.cpp:18 [backend fallback]
ADInplaceOrView: fallthrough registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:64 [backend fallback]
AutogradOther: fallthrough registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:35 [backend fallback]
AutogradCPU: fallthrough registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:39 [backend fallback]
AutogradCUDA: fallthrough registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:47 [backend fallback]
AutogradXLA: fallthrough registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:51 [backend fallback]
AutogradLazy: fallthrough registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:55 [backend fallback]
AutogradXPU: fallthrough registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:43 [backend fallback]
AutogradMLC: fallthrough registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:59 [backend fallback]
Tracer: registered at ../torch/csrc/autograd/TraceTypeManual.cpp:291 [backend fallback]
UNKNOWN_TENSOR_TYPE_ID: fallthrough registered at ../aten/src/ATen/autocast_mode.cpp:466 [backend fallback]
Autocast: fallthrough registered at ../aten/src/ATen/autocast_mode.cpp:305 [backend fallback]
Batched: registered at ../aten/src/ATen/BatchingRegistrations.cpp:1016 [backend fallback]
VmapMode: fallthrough registered at ../aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]


Exception raised from reportError at ../aten/src/ATen/core/dispatch/OperatorEntry.cpp:431 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f4760aefd62 in /data/disk1/ybZhang/.opendir/wenet2/runtime/binding/python/fc_base/libtorch-src/lib/libc10.so)
frame #1: c10::impl::OperatorEntry::reportError(c10::DispatchKey) const + 0x6f2 (0x7f47a55dafb2 in /data/disk1/ybZhang/.opendir/wenet2/runtime/binding/python/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #2: <unknown function> + 0x3e88796 (0x7f47a81c1796 in /data/disk1/ybZhang/.opendir/wenet2/runtime/binding/python/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #3: <unknown function> + 0x3bd0a59 (0x7f47a7f09a59 in /data/disk1/ybZhang/.opendir/wenet2/runtime/binding/python/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #4: torch::jit::InterpreterState::run(std::vector<c10::IValue, std::allocator<c10::IValue> >&) + 0x1c (0x7f47a7ef86fc in /data/disk1/ybZhang/.opendir/wenet2/runtime/binding/python/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #5: <unknown function> + 0x3bb7492 (0x7f47a7ef0492 in /data/disk1/ybZhang/.opendir/wenet2/runtime/binding/python/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #6: torch::jit::GraphFunction::operator()(std::vector<c10::IValue, std::allocator<c10::IValue> >, std::unordered_map<std::string, c10::IValue, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, c10::IValue> > > const&) + 0x39 (0x7f47a7c15509 in /data/disk1/ybZhang/.opendir/wenet2/runtime/binding/python/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0x3c5f1b5 (0x7f47a7f981b5 in /data/disk1/ybZhang/.opendir/wenet2/runtime/binding/python/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #8: <unknown function> + 0x3c60342 (0x7f47a7f99342 in /data/disk1/ybZhang/.opendir/wenet2/runtime/binding/python/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #9: <unknown function> + 0x3c96b20 (0x7f47a7fcfb20 in /data/disk1/ybZhang/.opendir/wenet2/runtime/binding/python/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #10: torch::jit::Unpickler::readInstruction() + 0x78f (0x7f47a7fd821f in /data/disk1/ybZhang/.opendir/wenet2/runtime/binding/python/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #11: torch::jit::Unpickler::run() + 0x90 (0x7f47a7fd9b20 in /data/disk1/ybZhang/.opendir/wenet2/runtime/binding/python/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #12: torch::jit::Unpickler::parse_ivalue() + 0x18 (0x7f47a7fd9c98 in /data/disk1/ybZhang/.opendir/wenet2/runtime/binding/python/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #13: torch::jit::readArchiveAndTensors(std::string const&, std::string const&, std::string const&, c10::optional<std::function<c10::StrongTypePtr (c10::QualifiedName const&)> >, c10::optional<std::function<c10::intrusive_ptr<c10::ivalue::Object, c10::detail::intrusive_target_default_null_type<c10::ivalue::Object> > (c10::StrongTypePtr, c10::IValue)> >, c10::optional<c10::Device>, caffe2::serialize::PyTorchStreamReader&, std::shared_ptr<torch::jit::DeserializationStorageContext>) + 0x4a0 (0x7f47a7f9aca0 in /data/disk1/ybZhang/.opendir/wenet2/runtime/binding/python/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #14: <unknown function> + 0x3c5b5fb (0x7f47a7f945fb in /data/disk1/ybZhang/.opendir/wenet2/runtime/binding/python/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #15: <unknown function> + 0x3c5d08a (0x7f47a7f9608a in /data/disk1/ybZhang/.opendir/wenet2/runtime/binding/python/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #16: torch::jit::load(std::shared_ptr<caffe2::serialize::ReadAdapterInterface>, c10::optional<c10::Device>, std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > >&) + 0x1af (0x7f47a7f9744f in /data/disk1/ybZhang/.opendir/wenet2/runtime/binding/python/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #17: torch::jit::load(std::string const&, c10::optional<c10::Device>, std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > >&) + 0xad (0x7f47a7f9941d in /data/disk1/ybZhang/.opendir/wenet2/runtime/binding/python/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #18: torch::jit::load(std::string const&, c10::optional<c10::Device>) + 0x54 (0x7f47a7f994f4 in /data/disk1/ybZhang/.opendir/wenet2/runtime/binding/python/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #19: wenet::TorchAsrModel::Read(std::string const&) + 0x144 (0x7f482793b1c4 in /data/disk1/ybZhang/.opendir/wenet2/runtime/binding/python/build/temp.linux-x86_64-cpython-38/api/libwenet_api.so)
frame #20: Recognizer::Recognizer(std::string const&) + 0x3f5 (0x7f4827892615 in /data/disk1/ybZhang/.opendir/wenet2/runtime/binding/python/build/temp.linux-x86_64-cpython-38/api/libwenet_api.so)
frame #21: wenet_init + 0x33 (0x7f482788b963 in /data/disk1/ybZhang/.opendir/wenet2/runtime/binding/python/build/temp.linux-x86_64-cpython-38/api/libwenet_api.so)
frame #22: <unknown function> + 0xfb9e (0x7f4827c08b9e in /home/ybZhang/miniconda3/envs/wenet/lib/python3.8/site-packages/_wenet.cpython-38-x86_64-linux-gnu.so)
frame #23: <unknown function> + 0x7aa0 (0x7f4827c00aa0 in /home/ybZhang/miniconda3/envs/wenet/lib/python3.8/site-packages/_wenet.cpython-38-x86_64-linux-gnu.so)
<omitting python frames>
frame #40: __libc_start_main + 0xf5 (0x7f482ed8a555 in /lib64/libc.so.6)

Exception ignored in: <function Decoder.__del__ at 0x7f475da11b80>
Traceback (most recent call last):
  File "/home/ybZhang/miniconda3/envs/wenet/lib/python3.8/site-packages/wenet/decoder.py", line 56, in __del__
    _wenet.wenet_free(self.d)
AttributeError: 'Decoder' object has no attribute 'd'

```

**Comment by robin1001** [comment]
The python binding does not support `quantized model` with GPU mode.

**Comment by v-yunbin** [comment]
@robin1001 it works with not quantized model， but gpu decoding is slow than cpu decoding.
```
gpu decode：
real    1m5.747s
user    0m47.806s
sys     0m16.468s
cpu decode：
real    0m39.771s
user    0m37.880s
sys     0m1.975s
```

**Comment by v-yunbin** [comment]
@robin1001 whether speed of my test on cpu and gpu is normal？
