### ISSUE TITLE
JSONDecodeError when resume training

### ISSUE THREAD

**Issue by affanmehmood** [wenet-e2e/wenet#1437]
I'm getting this error while resuming training from the multi_cn checkpoint.

`python ./wenet/train.py --symbol_table C:\Work\wenet\models\multi_cn_conformer\units.txt --config C:\Work\wenet\models\multi_cn_conformer\train.yaml --train_data C:\Work\wenet\examples\data_aishell\transcript\aishell_transcript_v0.8.txt --cv_data C:\Work\wenet\examples\data_aishell\transcript\aishell_transcript_v0.8.txt --model_dir C:\Work\wenet\models --checkpoint C:\Work\wenet\models\multi_cn_conformer\final.pt --num_workers 1`

the number of model params: 46789396
2022-09-07 16:34:34,722 INFO Checkpoint: loading from checkpoint C:\Work\wenet\models\aishell_conformer\final.pt for CPU
2022-09-07 16:34:35,124 INFO Checkpoint: save to checkpoint C:\Work\wenet\models\init.pt
2022-09-07 16:34:35,515 INFO Epoch 0 TRAIN info lr 4e-08
2022-09-07 16:34:35,517 INFO using accumulate grad, new batch size is 1 times larger than before
C:\Work\wenet\venv\lib\site-packages\torchaudio\backend\utils.py:62: UserWarning: No audio backend is available.
  warnings.warn("No audio backend is available.")
Traceback (most recent call last):
  File "C:\Work\wenet\wenet\train.py", line 297, in <module>
    main()
  File "C:\Work\wenet\wenet\train.py", line 269, in main
    executor.train(model, optimizer, scheduler, train_data_loader, device,
  File "C:\Work\wenet\wenet\utils\executor.py", line 54, in train
    for batch_idx, batch in enumerate(data_loader):
  File "C:\Work\wenet\venv\lib\site-packages\torch\utils\data\dataloader.py", line 681, in __next__
    data = self._next_data()
  File "C:\Work\wenet\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "C:\Work\wenet\venv\lib\site-packages\torch\utils\data\dataloader.py", line 1402, in _process_data
    data.reraise()
  File "C:\Work\wenet\venv\lib\site-packages\torch\_utils.py", line 460, in reraise
    raise RuntimeError(msg) from None
RuntimeError: Caught JSONDecodeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Work\wenet\venv\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Work\wenet\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 39, in fetch
    data = next(self.dataset_iter)
  File "C:\Work\wenet\wenet\dataset\processor.py", line 596, in padding
    for sample in data:
  File "C:\Work\wenet\wenet\dataset\processor.py", line 538, in static_batch
    for sample in data:
  File "C:\Work\wenet\wenet\dataset\processor.py", line 514, in sort
    for sample in data:
  File "C:\Work\wenet\wenet\dataset\processor.py", line 486, in shuffle
    for sample in data:
  File "C:\Work\wenet\wenet\dataset\processor.py", line 423, in spec_aug
    for sample in data:
  File "C:\Work\wenet\wenet\dataset\processor.py", line 266, in compute_fbank
    for sample in data:
  File "C:\Work\wenet\wenet\dataset\processor.py", line 238, in speed_perturb
    for sample in data:
  File "C:\Work\wenet\wenet\dataset\processor.py", line 213, in resample
    for sample in data:
  File "C:\Work\wenet\wenet\dataset\processor.py", line 180, in filter
    for sample in data:
  File "C:\Work\wenet\wenet\dataset\processor.py", line 372, in tokenize
    for sample in data:
  File "C:\Work\wenet\wenet\dataset\processor.py", line 124, in parse_raw
    obj = json.loads(json_line)
  File "C:\Users\affan\anaconda3\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\affan\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\affan\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by robin1001** [comment]
please make sure your data format is correct, please see https://wenet.org.cn/wenet/tutorial_librispeech.html#stage-3-prepare-wenet-data-format.
