### ISSUE TITLE
formats: can't open input file .flac

### ISSUE THREAD

**Issue by RyanGuo98** [wenet-e2e/wenet#1448]
hi, when i use my dataset is .flac .the   stage 1 is wrong,the error is below :
 stage 1: Feature Generation
using resample and new sample rate is 16000
formats: can't open input file `/root/share/data/Audios/5f5491c50b8b1.flac': No such file or directory
Traceback (most recent call last):
  File "tools/compute_cmvn_stats.py", line 124, in <module>
    for i, batch in enumerate(data_loader):
  File "/root/.local/conda/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/root/.local/conda/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/root/.local/conda/envs/wenet/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "tools/compute_cmvn_stats.py", line 37, in __call__
    sample_rate = torchaudio.backend.sox_io_backend.info(wav_path).sample_rate
  File "/root/.local/conda/envs/wenet/lib/python3.8/site-packages/torchaudio/backend/sox_io_backend.py", line 53, in info
    sinfo = torch.ops.torchaudio.sox_io_get_info(filepath, format)
RuntimeError: Error loading audio file: failed to open file /root/share/data/Audios/5f5491c50b8b1.flac
but my data is in the folder.i try to  change   torchaudio.set_audio_backend('soundfile')  in compute_cmvn_stats.py aand not work.

**Comment by RyanGuo98** [comment]
sorry, it's my faulty.the path is worry.
