### ISSUE TITLE
How to Creating two instances ? 

### ISSUE THREAD

**Issue by liqiujiong** [wenet-e2e/wenet#1459]
**Describe the bug**
Creating two instances  have problem

**To Reproduce**
1. import wenetruntime
2. wenetruntime.decode(lang='en')

**Expected behavior**
### Creating two instances is not supported?
```
    def __init__(self) -> None:
        self._wenet_zh = wenet.Decoder(
                        model_dir=model_dir_zh,
                        lang='chs',
                        nbest=1
                        )
        self._wenet_en = wenet.Decoder(
                        lang='en'
                        )
```
**Screenshots**
``` Traceback (most recent call last):
  File "A:\Code\a_SampleCode\rabbit-mq-test\main.py", line 7, in <module>
    wb = WenetBackend()
  File "A:\Code\a_SampleCode\rabbit-mq-test\lib\WenetService.py", line 17, in __init__
    self._wenet_en = None
  File "D:\Software\Conda\envs\myenv\lib\site-packages\wenetruntime\decoder.py", line 45, in __init__
    self.d = _wenet.wenet_init(model_dir)
RuntimeError: Error: cannot set number of interop threads after parallel work has started or set_num_interop_threads called
Exception raised from set_num_interop_threads at ..\..\aten\src\ATen\ParallelThreadPoolNative.cpp:56 (most recent call first):
00007FFF25C1A29200007FFF25C1A230 c10.dll!c10::Error::Error [<unknown file> @ <unknown line number>]
00007FFF25C19CAE00007FFF25C19C60 c10.dll!c10::detail::torchCheckFail [<unknown file> @ <unknown line number>]
00007FFDFD3E29DA00007FFDFD3E2960 torch_cpu.dll!at::set_num_interop_threads [<unknown file> @ <unknown line number>]
00007FFF22FA532400007FFF22F4A140 wenet_api.dll!wenet_set_timestamp [<unknown file> @ <unknown line number>]
00007FFF22F3976B00007FFF22F39480 wenet_api.dll!Recognizer::Recognizer [<unknown file> @ <unknown line number>]
00007FFF22F49FF300007FFF22F49F80 wenet_api.dll!wenet_init [<unknown file> @ <unknown line number>]
00007FFF25C713C000007FFF25C6BAC0 _wenet.cp39-win_amd64.pyd!PyInit__wenet [<unknown file> @ <unknown line number>]
00007FFF25C714C400007FFF25C6BAC0 _wenet.cp39-win_amd64.pyd!PyInit__wenet [<unknown file> @ <unknown line number>]
00007FFF25C6977800007FFF25C626C0 _wenet.cp39-win_amd64.pyd!pybind11::error_already_set::error_already_set [<unknown file> @ <unknown line number>]
00007FFF14266CDE00007FFF14264F74 python39.dll!PyArg_ParseTuple_SizeT [<unknown file> @ <unknown line number>]
00007FFF14238A7C00007FFF14237B10 python39.dll!Py_NewReference [<unknown file> @ <unknown line number>]
00007FFF14240D9B00007FFF142404E0 python39.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FFF1423A5B600007FFF14239C70 python39.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FFF14239EAD00007FFF14239C70 python39.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FFF1428A7DD00007FFF1428A51C python39.dll!PyObject_CallObject [<unknown file> @ <unknown line number>]
00007FFF142384E200007FFF14237B10 python39.dll!Py_NewReference [<unknown file> @ <unknown line number>]
00007FFF1424130800007FFF142404E0 python39.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FFF14239DE400007FFF14239C70 python39.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FFF1428A70200007FFF1428A51C python39.dll!PyObject_CallObject [<unknown file> @ <unknown line number>]
00007FFF142384E200007FFF14237B10 python39.dll!Py_NewReference [<unknown file> @ <unknown line number>]
00007FFF1424097200007FFF142404E0 python39.dll!PyEval_EvalFrameDefault [<unknown file> @ <unknown line number>]
00007FFF1423A5B600007FFF14239C70 python39.dll!PyFunction_Vectorcall [<unknown file> @ <unknown line number>]
00007FFF1428786900007FFF142877C0 python39.dll!PyEval_EvalCodeWithName [<unknown file> @ <unknown line number>]
00007FFF142877AB00007FFF14287710 python39.dll!PyEval_EvalCodeEx [<unknown file> @ <unknown line number>]
00007FFF1428770900007FFF142876DC python39.dll!PyEval_EvalCode [<unknown file> @ <unknown line number>]
00007FFF1428730A00007FFF14287174 python39.dll!PyType_LookupId [<unknown file> @ <unknown line number>]
00007FFF1428728A00007FFF14287174 python39.dll!PyType_LookupId [<unknown file> @ <unknown line number>]
00007FFF1437D4B700007FFF1437C300 python39.dll!PyUnicode_WriteChar [<unknown file> @ <unknown line number>]
00007FFF1425006000007FFF1424F63C python39.dll!PyLong_DivmodNear [<unknown file> @ <unknown line number>]
00007FFF142E8B5700007FFF142E8B08 python39.dll!PyRun_SimpleFileExFlags [<unknown file> @ <unknown line number>]
00007FFF142E898400007FFF142E8938 python39.dll!PyRun_AnyFileExFlags [<unknown file> @ <unknown line number>]
00007FFF142CC20A00007FFF142CC0B8 python39.dll!PyUnicode_EncodeFSDefault [<unknown file> @ <unknown line number>]
00007FFF142CB1B000007FFF142CB024 python39.dll!Py_RunMain [<unknown file> @ <unknown line number>]
00007FFF142CB03900007FFF142CB024 python39.dll!Py_RunMain [<unknown file> @ <unknown line number>]
00007FFF142CB6B200007FFF142CB2A0 python39.dll!Py_ClearArgcArgv [<unknown file> @ <unknown line number>]
00007FFF142CB9FD00007FFF142CB9D8 python39.dll!Py_Main [<unknown file> @ <unknown line number>]
00007FF74F181268 <unknown symbol address> python.exe!<unknown symbol> [<unknown file> @ <unknown line number>]
00007FFF6F7A703400007FFF6F7A7020 KERNEL32.DLL!BaseThreadInitThunk [<unknown file> @ <unknown line number>]
00007FFF70FA265100007FFF70FA2630 ntdll.dll!RtlUserThreadStart [<unknown file> @ <unknown line number>]

Exception ignored in: <function Decoder.__del__ at 0x00000242A8853E50>
Traceback (most recent call last):
  File "D:\Software\Conda\envs\myenv\lib\site-packages\wenetruntime\decoder.py", line 56, in __del__
    _wenet.wenet_free(self.d)
AttributeError: 'Decoder' object has no attribute 'd'

**Comment by robin1001** [comment]
Yes, creating multiple instance is not supported, you can try to use it in two processes.
