### ISSUE TITLE
Question about multi-machine training 

### ISSUE THREAD

**Issue by NathanJHLee** [wenet-e2e/wenet#1490]
Hi My name is Nathan and I am using Wenet for asr training.
I am very appreciate your work. Thank you.

These days, I try to work by multi-machine training based on "wenet-main/examples/aishell/rnnt/run.sh"
I checked single node training and it works fine.
Error occurred during num_nodes=2 

My environment.
1. There are two ip {xx.xxx.xx.110, xx.xxx.xx.111}
  - I call them as host 'asrA', 'asrB'
3. some open port(ex : 2376)
  -using firewall-cmd    #Centos 7 
4. Both nodes have [a100 gpu x 8] 

torch 1.10.0
nccl-2.7.8
cuda 11.1

------------------------------------------------------------
**run-1.sh**
num_nodes=2
node_rank=0
init_method=tcp://xx.xxx.xx.110:2376
dist_backend="nccl"

-------------------------------------------------------------
**run-2.sh**
num_nodes=2
node_rank=1
init_method=tcp://xx.xxx.xx.110:2376
dist_backend="nccl"

-------------------------------------------------------------

start&stop stage = 4
Run as below respectively(hosts)
[woker@**asrA**]$ nohup bash ./**run-1.sh** > **Multi_1.txt** &
[woker@**asrB**]$ nohup bash ./**run-2.sh** > **Multi_2.txt** &

**$cat Multi_1.txt**
total gpus is: 16
2022-10-12 01:39:20,998 INFO training on multiple gpus, this gpu 5
2022-10-12 01:39:21,014 INFO training on multiple gpus, this gpu 3
2022-10-12 01:39:21,020 INFO training on multiple gpus, this gpu 0
2022-10-12 01:39:21,041 INFO training on multiple gpus, this gpu 7
2022-10-12 01:39:21,046 INFO training on multiple gpus, this gpu 2
2022-10-12 01:39:21,086 INFO training on multiple gpus, this gpu 6
2022-10-12 01:39:21,119 INFO training on multiple gpus, this gpu 1
2022-10-12 01:39:21,123 INFO training on multiple gpus, this gpu 4
2022-10-12 01:39:34,988 INFO Added key: store_based_barrier_key:1 to store for rank: 5
2022-10-12 01:39:35,038 INFO Added key: store_based_barrier_key:1 to store for rank: 7
2022-10-12 01:39:35,087 INFO Added key: store_based_barrier_key:1 to store for rank: 6
2022-10-12 01:39:35,143 INFO Added key: store_based_barrier_key:1 to store for rank: 2
2022-10-12 01:39:35,213 INFO Added key: store_based_barrier_key:1 to store for rank: 1
2022-10-12 01:39:35,267 INFO Added key: store_based_barrier_key:1 to store for rank: 3
2022-10-12 01:39:35,324 INFO Added key: store_based_barrier_key:1 to store for rank: 4
2022-10-12 01:39:35,398 INFO Added key: store_based_barrier_key:1 to store for rank: 0
2022-10-12 01:39:39,224 INFO Rank 7: Completed store-based barrier for key:store_based_barrier_key:1 with 16 nodes.
2022-10-12 01:39:39,224 INFO Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 16 nodes.
2022-10-12 01:39:39,224 INFO Rank 6: Completed store-based barrier for key:store_based_barrier_key:1 with 16 nodes.
2022-10-12 01:39:39,224 INFO Rank 2: Completed store-based barrier for key:store_based_barrier_key:1 with 16 nodes.
2022-10-12 01:39:39,224 INFO Rank 4: Completed store-based barrier for key:store_based_barrier_key:1 with 16 nodes.
2022-10-12 01:39:39,224 INFO Rank 5: Completed store-based barrier for key:store_based_barrier_key:1 with 16 nodes.
2022-10-12 01:39:39,224 INFO Rank 1: Completed store-based barrier for key:store_based_barrier_key:1 with 16 nodes.
2022-10-12 01:39:39,224 INFO Rank 3: Completed store-based barrier for key:store_based_barrier_key:1 with 16 nodes.
2022-10-12 01:39:40,378 INFO Checkpoint: loading from checkpoint exp/conformer_rnnt/30.pt for GPU
2022-10-12 01:39:40,386 INFO Checkpoint: loading from checkpoint exp/conformer_rnnt/30.pt for GPU
2022-10-12 01:39:40,386 INFO Checkpoint: loading from checkpoint exp/conformer_rnnt/30.pt for GPU
2022-10-12 01:39:40,392 INFO Checkpoint: loading from checkpoint exp/conformer_rnnt/30.pt for GPU
2022-10-12 01:39:40,419 INFO Checkpoint: loading from checkpoint exp/conformer_rnnt/30.pt for GPU
2022-10-12 01:39:40,421 INFO Checkpoint: loading from checkpoint exp/conformer_rnnt/30.pt for GPU
2022-10-12 01:39:40,457 INFO Checkpoint: loading from checkpoint exp/conformer_rnnt/30.pt for GPU
2022-10-12 01:39:42,899 INFO Checkpoint: loading from checkpoint exp/conformer_rnnt/30.pt for GPU

**$cat Multi_2.txt**
total gpus is: 16
2022-10-12 01:37:15,429 INFO training on multiple gpus, this gpu 0
2022-10-12 01:37:15,429 INFO training on multiple gpus, this gpu 1
2022-10-12 01:37:15,429 INFO training on multiple gpus, this gpu 3
2022-10-12 01:37:15,438 INFO training on multiple gpus, this gpu 4
2022-10-12 01:37:15,449 INFO training on multiple gpus, this gpu 2
2022-10-12 01:37:15,494 INFO training on multiple gpus, this gpu 7
2022-10-12 01:37:15,500 INFO training on multiple gpus, this gpu 5
2022-10-12 01:37:15,566 INFO training on multiple gpus, this gpu 6
2022-10-12 01:37:29,441 INFO Added key: store_based_barrier_key:1 to store for rank: 9
2022-10-12 01:37:29,491 INFO Added key: store_based_barrier_key:1 to store for rank: 14
2022-10-12 01:37:29,559 INFO Added key: store_based_barrier_key:1 to store for rank: 8
2022-10-12 01:37:29,611 INFO Added key: store_based_barrier_key:1 to store for rank: 10
2022-10-12 01:37:29,666 INFO Added key: store_based_barrier_key:1 to store for rank: 11
2022-10-12 01:37:29,719 INFO Added key: store_based_barrier_key:1 to store for rank: 15
2022-10-12 01:37:29,774 INFO Added key: store_based_barrier_key:1 to store for rank: 13
2022-10-12 01:37:29,830 INFO Added key: store_based_barrier_key:1 to store for rank: 12
2022-10-12 01:37:29,831 INFO Rank 12: Completed store-based barrier for key:store_based_barrier_key:1 with 16 nodes.
2022-10-12 01:37:29,831 INFO Rank 8: Completed store-based barrier for key:store_based_barrier_key:1 with 16 nodes.
2022-10-12 01:37:29,831 INFO Rank 10: Completed store-based barrier for key:store_based_barrier_key:1 with 16 nodes.
2022-10-12 01:37:29,834 INFO Rank 11: Completed store-based barrier for key:store_based_barrier_key:1 with 16 nodes.
2022-10-12 01:37:29,835 INFO Rank 15: Completed store-based barrier for key:store_based_barrier_key:1 with 16 nodes.
2022-10-12 01:37:29,837 INFO Rank 13: Completed store-based barrier for key:store_based_barrier_key:1 with 16 nodes.
2022-10-12 01:37:29,837 INFO Rank 9: Completed store-based barrier for key:store_based_barrier_key:1 with 16 nodes.
2022-10-12 01:37:29,837 INFO Rank 14: Completed store-based barrier for key:store_based_barrier_key:1 with 16 nodes.
2022-10-12 01:37:30,758 INFO Checkpoint: loading from checkpoint exp/conformer_rnnt/30.pt for GPU
2022-10-12 01:37:31,029 INFO Checkpoint: loading from checkpoint exp/conformer_rnnt/30.pt for GPU
2022-10-12 01:37:31,030 INFO Checkpoint: loading from checkpoint exp/conformer_rnnt/30.pt for GPU
2022-10-12 01:37:31,034 INFO Checkpoint: loading from checkpoint exp/conformer_rnnt/30.pt for GPU
2022-10-12 01:37:31,039 INFO Checkpoint: loading from checkpoint exp/conformer_rnnt/30.pt for GPU
2022-10-12 01:37:31,039 INFO Checkpoint: loading from checkpoint exp/conformer_rnnt/30.pt for GPU
2022-10-12 01:37:31,040 INFO Checkpoint: loading from checkpoint exp/conformer_rnnt/30.pt for GPU
2022-10-12 01:37:31,049 INFO Checkpoint: loading from checkpoint exp/conformer_rnnt/30.pt for GPU
Transducer(
  (encoder): ConformerEncoder(

{.....model description......}

the number of model params: 52984612
Traceback (most recent call last):
  File "wenet/bin/train.py", line 297, in <module>
    main()
  File "wenet/bin/train.py", line 232, in main
    model, find_unused_parameters=True)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/parallel/distributed.py", line 578, in __init__
    dist._verify_model_across_ranks(self.process_group, parameters)
RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:957, unhandled system error, NCCL version 21.0.3
ncclSystemError: System call (socket, malloc, munmap, etc) failed.

I don't understand 'NCCL version 21.0.3' which belongs to second host's log
Please check this issue. Thank you.

**Comment by NathanJHLee** [comment]
I added 'os.environ['NCCL_DEBUG'] = 'INFO' to train.py
and checked nccl log.
Finally, solved problem.
It's because of port range.
Thank you.
