### ISSUE TITLE
python decode crash when using language model (LM)

### ISSUE THREAD

**Issue by eschmidbauer** [wenet-e2e/wenet#1515]
**Describe the bug**
I'm getting a crash when I run decode using python bindings and a LM
Here is the example script
```
import sys
import wenetruntime as wenet

wav_file = sys.argv[1]
decoder = wenet.Decoder(lang='en', model_dir='./pretrained')
ans = decoder.decode_wav(wav_file)
print(ans)
```
In  `pretrained/`
```
TLG.fst
words.txt
final.zip
units.txt
```

**To Reproduce**
`GLOG_v=2 GLOG_logtostderr=1 python decode.py test.wav`
```
I1021 16:48:59.956578 4106891 asr_decoder.cc:194] Partial CTC result z
Traceback (most recent call last):
  File "/root/_wenet_decode/decode.py", line 6, in <module>
    ans = decoder.decode_wav(wav_file)
  File "/root/miniconda3/envs/wenet/lib/python3.10/site-packages/wenetruntime-1.0.8-py3.10-linux-x86_64.egg/wenetruntime/decoder.py", line 114, in decode_wav
    return self.decode(wav, True)
  File "/root/miniconda3/envs/wenet/lib/python3.10/site-packages/wenetruntime-1.0.8-py3.10-linux-x86_64.egg/wenetruntime/decoder.py", line 96, in decode
    _wenet.wenet_decode(self.d, pcm, len(pcm), finish)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/wenet/transformer/asr_model.py", line 104, in forward_attention_decoder
    _20 = _14(r_hyps0, self.sos, self.eos, self.ignore_id, )
    r_hyps1, _21, = _20
    _22 = (self.decoder).forward(encoder_out0, encoder_mask, hyps, hyps_lens, r_hyps1, reverse_weight, )
           ~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    decoder_out, r_decoder_out, _23, = _22
    decoder_out0 = _15(decoder_out, -1, 3, None, )
  File "code/__torch__/wenet/transformer/decoder.py", line 15, in forward
    r_ys_in_pad: Tensor,
    reverse_weight: float=0.) -> Tuple[Tensor, Tensor, Tensor]:
    _0 = (self.left_decoder).forward(memory, memory_mask, ys_in_pad, ys_in_lens, None, 0., )
          ~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    l_x, _1, olens, = _0
    r_x = torch.tensor(0.)
  File "code/__torch__/wenet/transformer/decoder.py", line 53, in forward
    m = torch.unsqueeze(_7, 0)
    tgt_mask1 = torch.__and__(tgt_mask0, m)
    x, _8, = (self.embed).forward(ys_in_pad, )
              ~~~~~~~~~~~~~~~~~~~ <--- HERE
    _9 = self.decoders
    _10 = getattr(_9, "0")
  File "code/__torch__/torch/nn/modules/container/___torch_mangle_4.py", line 12, in forward
    _0 = getattr(self, "0")
    _1 = getattr(self, "1")
    input0 = (_0).forward(input, )
              ~~~~~~~~~~~ <--- HERE
    return (_1).forward(input0, 0, )
  def __len__(self: __torch__.torch.nn.modules.container.___torch_mangle_4.Sequential) -> int:
  File "code/__torch__/torch/nn/modules/sparse.py", line 17, in forward
    input: Tensor) -> Tensor:
    _0 = __torch__.torch.nn.functional.embedding
    _1 = _0(input, self.weight, None, None, 2., False, False, )
         ~~ <--- HERE
    return _1
  File "code/__torch__/torch/nn/functional.py", line 206, in embedding
  else:
    input0 = input
  _42 = torch.embedding(weight, input0, padding_idx0, scale_grad_by_freq, sparse)
        ~~~~~~~~~~~~~~~ <--- HERE
  return _42
def ctc_loss(log_probs: Tensor,

Traceback of TorchScript, original code (most recent call last):
  File "/home/binbzha/miniconda3/envs/wenet/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    def forward(self, input):
        for module in self:
            input = module(input)
                    ~~~~~~ <--- HERE
        return input
  File "/home/binbzha/miniconda3/envs/wenet/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 158, in forward
    def forward(self, input: Tensor) -> Tensor:
        return F.embedding(
               ~~~~~~~~~~~ <--- HERE
            input, self.weight, self.padding_idx, self.max_norm,
            self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/home/binbzha/miniconda3/envs/wenet/lib/python3.8/site-packages/torch/nn/functional.py", line 2043, in embedding
        # remove once script supports set_grad_enabled
        _no_grad_embedding_renorm_(weight, input, max_norm, norm_type)
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
           ~~~~~~~~~~~~~~~ <--- HERE
RuntimeError: index out of range in self
```

**Additional context**
CPU Only environment, python3

**Comment by robin1001** [comment]
Please first check that the modeling unit(units.txt) and the model(final.zip) are consistent. If it works, then check if you get `words.txt` and `TLG.fst` in right way.

**Comment by eschmidbauer** [comment]
> Please first check that the modeling unit(units.txt) and the model(final.zip) are consistent. 
Can you tell me how to check if they are consistent?

**Comment by robin1001** [comment]
Only put units.txt and final.zip  in your model dir, then run to see if it works.

**Comment by eschmidbauer** [comment]
> Only put units.txt and final.zip in your model dir, then run to see if it works.

Without the LM loaded, the model works. 
Im using a librespeech LM with a gigaspeech runtime model. Should that work? 
Does anyone have any English pretrained/runtime LMs that are known to work with the gigaspeech model that they could share?

**Comment by xingchensong** [comment]
> 

 The librispeech LM  and gigaspeech runtime model do not share the same `units.txt`, please rebulid TLG.fst using gigaspeech units
