### ISSUE TITLE
Decoding step (step 5) on gigaspeech recipe fails

### ISSUE THREAD

**Issue by feddybear** [wenet-e2e/wenet#1539]
**Describe the bug**
I've finished training and is now testing the trained model on a test set.  When I run step 5, I get an error:
```
Traceback (most recent call last):
  File "wenet/bin/recognize.py", line 357, in <module>
    main()
  File "wenet/bin/recognize.py", line 198, in main
    test_dataset = Dataset(args.data_type,
  File "/workspace/wenet/wenet/dataset/dataset.py", line 138, in Dataset
    lists = read_lists(data_list_file)
  File "/workspace/wenet/wenet/utils/file_utils.py", line 20, in read_lists
    with open(list_file, 'r', encoding='utf8') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'data/test/format.data'
```
I don't know wherever this `format.data` was referenced in the scripts and tutorials.  It seems the recipes are not being updated alongside changes to the codebase...

**To Reproduce**
1. Finish training gigaspeech on step 4
2. Run step 5
3. See error

**Expected behavior**
Decoding will happen.

**Screenshots**
Error code should be sufficient.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 20.04

**Comment by feddybear** [comment]
I replaced step 5 on gigaspeech recipe with step 5 from wenetspeech recipe, and it's working.
