### ISSUE TITLE
recognize.py stops on error caused by short segments

### ISSUE THREAD

**Issue by feddybear** [wenet-e2e/wenet#1542]
**Describe the bug**
When I run `recognize.py` for evaluation, I come across segments that are very short (e.g. 0.12 seconds), I will get the following error, and the decoding will halt:
```
Traceback (most recent call last):
  File "wenet/bin/recognize.py", line 357, in <module>
    main()
  File "wenet/bin/recognize.py", line 313, in main
    hyp, _ = model.attention_rescoring(
  File "/workspace/wenet/wenet/transformer/asr_model.py", line 493, in attention_rescoring
    hyps, encoder_out = self._ctc_prefix_beam_search(
  File "/workspace/wenet/wenet/transformer/asr_model.py", line 369, in _ctc_prefix_beam_search
    encoder_out, encoder_mask = self._forward_encoder(
  File "/workspace/wenet/wenet/transformer/asr_model.py", line 175, in _forward_encoder
    encoder_out, encoder_mask = self.encoder(
  File "/opt/miniconda/envs/wenet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/wenet/wenet/transformer/encoder.py", line 164, in forward
    xs, pos_emb, masks = self.embed(xs, masks)
  File "/opt/miniconda/envs/wenet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/wenet/wenet/transformer/subsampling.py", line 181, in forward
    x = self.conv(x)
  File "/opt/miniconda/envs/wenet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/miniconda/envs/wenet/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/opt/miniconda/envs/wenet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/miniconda/envs/wenet/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/opt/miniconda/envs/wenet/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 442, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Calculated padded input size per channel: (4 x 39). Kernel size: (5 x 5). Kernel size can't be greater than actual input size
```
what can we do so that instead of stopping, it just skips and return an empty output?

**To Reproduce**
1. Run recognize.py on any recipe with a test set containing very short segments
2. See error

**Expected behavior**
Warning, and skip file/segment

**Screenshots**
Error snippet should be sufficient

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 20.04

**Comment by robin1001** [comment]
Just drop the sentences which are very short.

**Comment by robin1001** [comment]
If it is two short, it can not gives even one output after subsampling, then it fails to decode.
