### ISSUE TITLE
RuntimeError: expected scalar type Long but found Int

### ISSUE THREAD

**Issue by kakushawn** [wenet-e2e/wenet#1547]
**Describe the bug**
This error occurred sometimes when running `attention_rescoring` when doing inference with cuda.

**To Reproduce**
Since it doesn't happen every time, what I found is in https://github.com/wenet-e2e/wenet/blob/1d9b0bf066aae3170c8c084ead6260f1f76b4fe5/wenet/transformer/asr_model.py#L124
The `r_ys_pad ` sent to https://github.com/wenet-e2e/wenet/blob/1d9b0bf066aae3170c8c084ead6260f1f76b4fe5/wenet/transformer/asr_model.py#L137
will cause this bug happen when some of the element in `r_ys_pad` is emtpy when running with cuda.
Maybe the `torch.cat()` method in https://github.com/wenet-e2e/wenet/blob/1d9b0bf066aae3170c8c084ead6260f1f76b4fe5/wenet/utils/common.py#L131
have different behavior when concatenating empty list when using cpu vs cuda.

**Screenshots**
I simply copied and pasted the error message here:

Traceback (most recent call last):
  File "wenet/bin/recognize.py", line 314, in <module>
    main()
  File "wenet/bin/recognize.py", line 293, in main
    hyp, _ = model.attention_rescoring(
  File "/project/wenet/wenet/transformer/asr_model.py", line 508, in attention_rescoring
    r_hyps_pad, _ = add_sos_eos(r_hyps_pad, self.sos, self.eos,
  File "/project/wenet/wenet/utils/common.py", line 135, in add_sos_eos
    ys_in = [torch.cat([_sos, y], dim=0) for y in ys]
  File "/project/wenet/wenet/utils/common.py", line 135, in <listcomp>
    ys_in = [torch.cat([_sos, y], dim=0) for y in ys]
RuntimeError: expected scalar type Long but found Int

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04
 - Version:
     1. wenet on `960728e`
     3. cuda: 10.2
     4. torch: 1.12.0

**Additional context**
My workaround solution is to simply remove the `.int()` in https://github.com/wenet-e2e/wenet/blob/1d9b0bf066aae3170c8c084ead6260f1f76b4fe5/wenet/utils/common.py#L158
, but maybe there is a more general way to fix this?

**Comment by donstang** [comment]
I meet the same problem, how to solve it?

**Comment by donstang** [comment]
> kakushawn

I meet the same problem, how to solve it?

**Comment by kakushawn** [comment]
> > kakushawn
> 
> I meet the same problem, how to solve it?

remove the `.int()` as mentioned
