### ISSUE TITLE
windows环境下编译不通过问题

### ISSUE THREAD

**Issue by elf7856** [wenet-e2e/wenet#1584]
我安装了cmake和mingGW64 然后编译wenet，报找不到库问题

(base) PS C:\Users\62583\Downloads\wenet-main\wenet-main\runtime\binding\python> python .\setup.py install --user
running install
C:\Users\62583\miniconda3\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
C:\Users\62583\miniconda3\lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing wenetruntime.egg-info\PKG-INFO
writing dependency_links to wenetruntime.egg-info\dependency_links.txt
writing requirements to wenetruntime.egg-info\requires.txt
writing top-level names to wenetruntime.egg-info\top_level.txt
reading manifest file 'wenetruntime.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'wenetruntime.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
Setting PYTHON_EXECUTABLE to C:\Users\62583\miniconda3\python.exe
CMake Error at CMakeLists.txt:28 (include):
  include could not find requested file:

    libtorch

CMake Error at CMakeLists.txt:29 (include):
  include could not find requested file:

    openfst

CMake Error at CMakeLists.txt:30 (include):
  include could not find requested file:

    pybind11

CMake Error at CMakeLists.txt:37 (add_subdirectory):
  add_subdirectory given source "utils" which is not an existing directory.

CMake Error at CMakeLists.txt:38 (add_subdirectory):
  add_subdirectory given source "frontend" which is not an existing
  directory.

CMake Error at CMakeLists.txt:39 (add_subdirectory):
  add_subdirectory given source "post_processor" which is not an existing
  directory.

CMake Error at CMakeLists.txt:40 (add_subdirectory):
  add_subdirectory given source "kaldi" which is not an existing directory.

CMake Error at CMakeLists.txt:41 (add_subdirectory):
  add_subdirectory given source "decoder" which is not an existing directory.

CMake Error at CMakeLists.txt:42 (add_subdirectory):
  add_subdirectory given source "api" which is not an existing directory.

CMake Error at CMakeLists.txt:45 (pybind11_add_module):
  Unknown CMake command "pybind11_add_module".

-- Configuring incomplete, errors occurred!
See also "C:/Users/62583/Downloads/wenet-main/wenet-main/runtime/binding/python/build/temp.win-amd64-3.9/Release/CMakeFiles/CMakeOutput.log".
mingw32-make.exe: Makefile: No such file or directory
mingw32-make.exe: *** No rule to make target 'Makefile'.  Stop.
Traceback (most recent call last):
  File "C:\Users\62583\Downloads\wenet-main\wenet-main\runtime\binding\python\setup.py", line 85, in <module>
    setuptools.setup(
  File "C:\Users\62583\miniconda3\lib\site-packages\setuptools\__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\62583\miniconda3\lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
    return run_commands(dist)
  File "C:\Users\62583\miniconda3\lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
    dist.run_commands()
  File "C:\Users\62583\miniconda3\lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "C:\Users\62583\miniconda3\lib\site-packages\setuptools\dist.py", line 1214, in run_command
    super().run_command(command)
  File "C:\Users\62583\miniconda3\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
    cmd_obj.run()
  File "C:\Users\62583\miniconda3\lib\site-packages\setuptools\command\install.py", line 74, in run
    self.do_egg_install()
  File "C:\Users\62583\miniconda3\lib\site-packages\setuptools\command\install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\62583\miniconda3\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\62583\miniconda3\lib\site-packages\setuptools\dist.py", line 1214, in run_command
    super().run_command(command)
  File "C:\Users\62583\miniconda3\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
    cmd_obj.run()
  File "C:\Users\62583\miniconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\62583\miniconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "C:\Users\62583\miniconda3\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\62583\miniconda3\lib\site-packages\setuptools\dist.py", line 1214, in run_command
    super().run_command(command)
  File "C:\Users\62583\miniconda3\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
    cmd_obj.run()
  File "C:\Users\62583\miniconda3\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\62583\miniconda3\lib\site-packages\setuptools\_distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\62583\miniconda3\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\62583\miniconda3\lib\site-packages\setuptools\dist.py", line 1214, in run_command
    super().run_command(command)
  File "C:\Users\62583\miniconda3\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
    cmd_obj.run()
  File "C:\Users\62583\miniconda3\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "C:\Users\62583\miniconda3\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "C:\Users\62583\miniconda3\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\62583\miniconda3\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\62583\Downloads\wenet-main\wenet-main\runtime\binding\python\setup.py", line 42, in build_extension
    raise Exception(
Exception:
Build wenet failed. Please check the error message.
You can ask for help by creating an issue on GitHub.

Click:
    https://github.com/wenet-e2e/wenet/issues/new

**Comment by elf7856** [comment]
> 

谢谢，我改用了msvc，但是还是会报这个错误

PS C:\Users\mobvoi\wenet\runtime\binding\python> python .\setup.py install --user
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
  warnings.warn(
WARNING: The wheel package is not available.
WARNING: The wheel package is not available.
running install
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing wenetruntime.egg-info\PKG-INFO
writing dependency_links to wenetruntime.egg-info\dependency_links.txt
writing requirements to wenetruntime.egg-info\requires.txt
writing top-level names to wenetruntime.egg-info\top_level.txt
reading manifest file 'wenetruntime.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'wenetruntime.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build
creating build\lib.win-amd64-cpython-310
creating build\lib.win-amd64-cpython-310\wenetruntime
copying py\decoder.py -> build\lib.win-amd64-cpython-310\wenetruntime
copying py\hub.py -> build\lib.win-amd64-cpython-310\wenetruntime
copying py\__init__.py -> build\lib.win-amd64-cpython-310\wenetruntime
running build_ext
Setting PYTHON_EXECUTABLE to C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe 
-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
-- The C compiler identification is MSVC 19.33.31630.0
-- The CXX compiler identification is MSVC 19.33.31630.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:28 (include):
  include could not find requested file:

    libtorch


CMake Error at CMakeLists.txt:29 (include):
  include could not find requested file:

    openfst


CMake Error at CMakeLists.txt:30 (include):
  include could not find requested file:

    pybind11


CMake Error at CMakeLists.txt:37 (add_subdirectory):
  add_subdirectory given source "utils" which is not an existing directory.


CMake Error at CMakeLists.txt:38 (add_subdirectory):
  add_subdirectory given source "frontend" which is not an existing
  directory.


CMake Error at CMakeLists.txt:39 (add_subdirectory):
  add_subdirectory given source "post_processor" which is not an existing
  directory.


CMake Error at CMakeLists.txt:40 (add_subdirectory):
  add_subdirectory given source "kaldi" which is not an existing directory.


CMake Error at CMakeLists.txt:41 (add_subdirectory):
  add_subdirectory given source "decoder" which is not an existing directory.


CMake Error at CMakeLists.txt:42 (add_subdirectory):
  add_subdirectory given source "api" which is not an existing directory.


CMake Error at CMakeLists.txt:45 (pybind11_add_module):
  Unknown CMake command "pybind11_add_module".


-- Configuring incomplete, errors occurred!
See also "C:/Users/mobvoi/wenet/runtime/binding/python/build/temp.win-amd64-cpython-310/Release/CMakeFiles/CMakeOutput.log".
MSBuild version 17.3.1+2badb37d1 for .NET Framework
MSBUILD : error MSB1009: 项目文件不存在。
开关:_wenet.vcxproj
Traceback (most recent call last):
  File "C:\Users\mobvoi\wenet\runtime\binding\python\setup.py", line 85, in <module>
    setuptools.setup(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\_distutils\core.py", line 177, in setup
    return run_commands(dist)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\_distutils\core.py", line 193, in run_commands
    dist.run_commands()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\dist.py", line 1217, in run_command
    super().run_command(command)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
    cmd_obj.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\command\install.py", line 74, in run
    self.do_egg_install()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\command\install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\_distutils\cmd.py", line 317, in run_command
    self.distribution.run_command(command)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\dist.py", line 1217, in run_command
    super().run_command(command)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
    cmd_obj.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\command\bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\command\bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\_distutils\cmd.py", line 317, in run_command
    self.distribution.run_command(command)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\dist.py", line 1217, in run_command
    super().run_command(command)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
    cmd_obj.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\_distutils\command\install_lib.py", line 112, in build
    self.run_command('build_ext')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\_distutils\cmd.py", line 317, in run_command
    self.distribution.run_command(command)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\dist.py", line 1217, in run_command
    super().run_command(command)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
    cmd_obj.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 459, in build_extensions
    self._build_extensions_serial()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 485, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\mobvoi\wenet\runtime\binding\python\setup.py", line 42, in build_extension
    raise Exception(
Exception:
Build wenet failed. Please check the error message.
You can ask for help by creating an issue on GitHub.

Click:
    https://github.com/wenet-e2e/wenet/issues/new

**Comment by elf7856** [comment]
那个找库的问题解决了，现在又报一个找不到mkl的问题，我已经在conda中安装了mkl，但是还是在报这个问题

-- MKL_ARCH: intel64
-- MKL_ROOT C:/Users/62583/miniconda3/Library
-- MKL_LINK: dynamic
-- MKL_INTERFACE_FULL: intel_ilp64
-- MKL_THREADING: intel_thread
-- MKL_MPI: intelmpi
CMake Error at C:/Users/62583/miniconda3/Library/lib/cmake/mkl/MKLConfig.cmake:618 (message):
  mkl_core.*.dll not found
Call Stack (most recent call first):
  fc_base/libtorch-src/share/cmake/Caffe2/public/mkl.cmake:1 (find_package)
  fc_base/libtorch-src/share/cmake/Caffe2/Caffe2Config.cmake:113 (include)
  fc_base/libtorch-src/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  C:/Users/62583/Downloads/wenet/runtime/core/cmake/libtorch.cmake:54 (find_package)
  CMakeLists.txt:28 (include)


-- Configuring incomplete, errors occurred!
See also "C:/Users/62583/Downloads/wenet/runtime/binding/python/build/temp.win-amd64-3.9/Release/CMakeFiles/CMakeOutput.log".
See also "C:/Users/62583/Downloads/wenet/runtime/binding/python/build/temp.win-amd64-3.9/Release/CMakeFiles/CMakeError.log".
MSBuild version 17.4.0+18d5aef85 for .NET Framework
MSBUILD : error MSB1009: 项目文件不存在。

**Comment by pengzhendong** [comment]
解决不了的环境问题，建议使用 github actions 来编译，然后上传编译结果

**Comment by elf7856** [comment]
谢谢，这个编译问题我已经解决了，是我的环境里没有mkl，后来下了一个放到编译环境里就解决了

**Comment by hhxdestiny** [comment]
> 谢谢，这个编译问题我已经解决了，是我的环境里没有mkl，后来下了一个放到编译环境里就解决了

请问编译x64有没有遇到以下问题
```bash
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.24/Modules/FetchContent.cmake:1267 (message):
  The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
  not set.  The policy's OLD behavior will be used.  When using a URL
  download, the timestamps of extracted files should preferably be that of
  the time of extraction, otherwise code that depends on the extracted
  contents might not be rebuilt if the URL changes.  The OLD behavior
  preserves the timestamps from the archive instead, but this is usually not
  what you want.  Update your project to the NEW behavior or specify the
  DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this
  robustness issue.
Call Stack (most recent call first):
  cmake/libtorch.cmake:49 (FetchContent_Declare)
  CMakeLists.txt:36 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Populating libtorch
CMake Error: Error: generator platform: x64
Does not match the platform used previously:
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
CMake Error at C:/Program Files/CMake/share/cmake-3.24/Modules/FetchContent.cmake:1592 (message):
  CMake step for libtorch failed: 1
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.24/Modules/FetchContent.cmake:1744:EVAL:2 (__FetchContent_directPopulate)
  C:/Program Files/CMake/share/cmake-3.24/Modules/FetchContent.cmake:1744 (cmake_language)
  C:/Program Files/CMake/share/cmake-3.24/Modules/FetchContent.cmake:1958 (FetchContent_Populate)
  cmake/libtorch.cmake:53 (FetchContent_MakeAvailable)
  CMakeLists.txt:36 (include)


-- Configuring incomplete, errors occurred!
```

**Comment by 1311004771** [comment]
> 谢谢，这个编译问题我已经解决了，是我的环境里没有mkl，后来下了一个放到编译环境里就解决了

您好，能具体说一下是怎么做的吗？我也遇到了这个问题..
![image](https://github.com/wenet-e2e/wenet/assets/93832987/f90314bc-940a-4043-9ae6-501507c03f27)

**Comment by yangy996** [comment]
大佬，请问怎么解决软连接的问题？我也报同样的错误
