### ISSUE TITLE
undefined value chunk_masks: in squeezformer

### ISSUE THREAD

**Issue by senbukai0203** [wenet-e2e/wenet#1628]
Just pulled the latest wenet code and tried out Squeezformer. The training is failed with this log attached below. Any suggestion would be helpful. Thanks. 

`the number of model params: 135,220,418
Traceback (most recent call last):
  File "wenet/bin/train.py", line 309, in <module>
    main()
  File "wenet/bin/train.py", line 205, in main
    script_model = torch.jit.script(model)
  File "/home/bsen/miniconda3/envs/wenet/lib/python3.8/site-packages/torch/jit/_script.py", line 1257, in script
    return torch.jit._recursive.create_script_module(
  File "/home/bsen/miniconda3/envs/wenet/lib/python3.8/site-packages/torch/jit/_recursive.py", line 451, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/home/bsen/miniconda3/envs/wenet/lib/python3.8/site-packages/torch/jit/_recursive.py", line 517, in create_script_module_impl
    create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
  File "/home/bsen/miniconda3/envs/wenet/lib/python3.8/site-packages/torch/jit/_recursive.py", line 368, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
  File "/home/bsen/miniconda3/envs/wenet/lib/python3.8/site-packages/torch/jit/_recursive.py", line 869, in compile_unbound_method
    create_methods_and_properties_from_stubs(concrete_type, (stub,), ())
  File "/home/bsen/miniconda3/envs/wenet/lib/python3.8/site-packages/torch/jit/_recursive.py", line 368, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
RuntimeError: 
undefined value **chunk_masks:**
  File "/home/bsen/wenet_new/examples/squeezformer/wenet/squeezeformer/encoder.py", line 379
                    pos_emb = recover_pos_emb
                    mask_pad = recover_mask_pad
                    xs = xs.masked_fill(~chunk_masks[:, 0, :].unsqueeze(-1), 0.0)
                                         ~~~~~~~~~~~ <--- HERE
    
            factor = self.calculate_downsampling_factor(i)
'SqueezeformerEncoder.forward_chunk' is being compiled since it was called from 'ASRModel.forward_encoder_chunk'
  File "/home/bsen/wenet_new/examples/squeezformer/wenet/transformer/asr_model.py", line 776
    
        """
        return self.encoder.forward_chunk(xs, offset, required_cache_size,
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                          att_cache, cnn_cache)
                                          ~~~~~~~~~~~~~~~~~~~~ <--- HERE`

**Comment by robin1001** [comment]
@yygle, please fix the issue.

**Comment by yygle** [comment]
Thanks for the issue!
https://github.com/wenet-e2e/wenet/pull/1629
