### ISSUE TITLE
undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE

### ISSUE THREAD

**Issue by arthurwu4work** [wenet-e2e/wenet#1644]
Hi 

I run the following script

```
import sys
import torch
import wenetruntime as wenet

wav_file = '/media/D/wave_data/test/Scenario_amr_poc2/record_test_Scenario_amr_poc2_01.wav'
model_dir = '/media/D/E2E/wenet/pretrain/runtime/wenetspeech_20220506_u2pp_conformer_libtorch'
decoder = wenet.Decoder(model_dir,
                        lang='chs',
                        nbest=5,
                        enable_timestamp=True,
                        context=['九', '刪除', '網路線', '十', '茶', '壺'],
                        context_score=3.0)
ans = decoder.decode_wav(wav_file)
print(ans)
```

but I get error

```
Traceback (most recent call last):
  File "run_pretrain.py", line 4, in <module>
    import wenetruntime as wenet
  File "/home/arthurwu/anaconda3/envs/py38_wenet/lib/python3.8/site-packages/wenetruntime/__init__.py", line 1, in <module>
    from .decoder import Decoder  # noqa
  File "/home/arthurwu/anaconda3/envs/py38_wenet/lib/python3.8/site-packages/wenetruntime/decoder.py", line 17, in <module>
    import _wenet
ImportError: /home/arthurwu/anaconda3/envs/py38_wenet/lib/python3.8/site-packages/wenetruntime.libs/libwenet_api-2ea698ed.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE
```

my environment

linux 20.04
python 3.8
torch 1.10.0
wenetruntime 1.10.0
CUDA 11.0

thx

**Comment by robin1001** [comment]
@pengzhendong is it a pytorch version problem?

**Comment by arthurwu4work** [comment]
Hi @pengzhendong ,

I reinstall wenetruntime==1.10.0 again, but i get the same error


torch version
```
(py38_wenet) arthurwu@arthurwu-pc:/media/D/E2E/wenet$ python
Python 3.8.15 (default, Nov 24 2022, 15:19:38) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.__version__)
1.10.0
>>> 
```

thx

**Comment by 2choonghyeon** [comment]
Hi. Did you fix this problem? I'm stuck with this same problem.

**Comment by DaobinZhu** [comment]
> Hi. Did you fix this problem? I'm stuck with this same problem.

Hi, have you solve this problems? i meet the same problems.

**Comment by duj12** [comment]
@arthurwu4work I meet the same problem, with torch==1.13.1+cu117,.
After I downgrade to torch==1.11.0+cu113, this issue is solved.
