### ISSUE TITLE
GPU runtime crash when decoding a specific standard WAV...

### ISSUE THREAD

**Issue by duj12** [wenet-e2e/wenet#1702]
When decoding with GPU runtime(ONNX-GPU model), I can decode some WAVs normally.

BUT when I decode the following wav, the program crashed.
[asrtest_xiangyu_0001.zip](https://github.com/wenet-e2e/wenet/files/10799483/asrtest_xiangyu_0001.zip)

TO Reproduce:

`/ws/client# python3 myclient.py    --audio_file=/ws/test_data/asrtest_xiangyu_0001.wav   --model_name=streaming_wenet --streaming`

myclient.py is the SingleThread-version of 'client.py'. Because when the crashing happens, the client.py doesn't give the real error codes.

The error message is like :

```
Traceback (most recent call last):
  File "myclient.py", line 148, in <module>
    predictions = single_job(filenames)
  File "myclient.py", line 141, in single_job
    result = speech_client.recognize(li, idx)
  File "/ws/client/speech_client.py", line 117, in recognize
    response = self.triton_client.infer(self.model_name,
  File "/usr/local/lib/python3.8/dist-packages/tritonclient/grpc/__init__.py", line 1295, in infer
    raise_error_grpc(rpc_error)
  File "/usr/local/lib/python3.8/dist-packages/tritonclient/grpc/__init__.py", line 62, in raise_error_grpc
    raise get_error_grpc(rpc_error) from None
tritonclient.utils.InferenceServerException: [StatusCode.INTERNAL] in ensemble 'streaming_wenet', Failed to process the request(s) for model instance 'wenet_0_1', message: TypeError: Wrong number or type of arguments for overloaded function 'ctc_beam_search_decoder_batch'.
  Possible C/C++ prototypes are:
    ctc_beam_search_decoder_batch(std::vector< std::vector< std::vector< double,std::allocator< double > >,std::allocator< std::vector< double,std::allocator< double > > > >,std::allocator< std::vector< std::vector< double,std::allocator< double > >,std::allocator< std::vector< double,std::allocator< double > > > > > > const &,std::vector< std::vector< std::vector< int,std::allocator< int > >,std::allocator< std::vector< int,std::allocator< int > > > >,std::allocator< std::vector< std::vector< int,std::allocator< int > >,std::allocator< std::vector< int,std::allocator< int > > > > > > const &,std::vector< PathTrie *,std::allocator< PathTrie * > > &,std::vector< bool,std::allocator< bool > > const &,size_t,size_t,int,int,double,Scorer *)
    ctc_beam_search_decoder_batch(std::vector< std::vector< std::vector< double,std::allocator< double > >,std::allocator< std::vector< double,std::allocator< double > > > >,std::allocator< std::vector< std::vector< double,std::allocator< double > >,std::allocator< std::vector< double,std::allocator< double > > > > > > const &,std::vector< std::vector< std::vector< int,std::allocator< int > >,std::allocator< std::vector< int,std::allocator< int > > > >,std::allocator< std::vector< std::vector< int,std::allocator< int > >,std::allocator< std::vector< int,std::allocator< int > > > > > > const &,std::vector< PathTrie *,std::allocator< PathTrie * > > &,std::vector< bool,std::allocator< bool > > const &,size_t,size_t,int,int,double)
    ctc_beam_search_decoder_batch(std::vector< std::vector< std::vector< double,std::allocator< double > >,std::allocator< std::vector< double,std::allocator< double > > > >,std::allocator< std::vector< std::vector< double,std::allocator< double > >,std::allocator< std::vector< double,std::allocator< double > > > > > > const &,std::vector< std::vector< std::vector< int,std::allocator< int > >,std::allocator< std::vector< int,std::allocator< int > > > >,std::allocator< std::vector< std::vector< int,std::allocator< int > >,std::allocator< std::vector< int,std::allocator< int > > > > > > const &,std::vector< PathTrie *,std::allocator< PathTrie * > > &,std::vector< bool,std::allocator< bool > > const &,size_t,size_t,int,int)
    ctc_beam_search_decoder_batch(std::vector< std::vector< std::vector< double,std::allocator< double > >,std::allocator< std::vector< double,std::allocator< double > > > >,std::allocator< std::vector< std::vector< double,std::allocator< double > >,std::allocator< std::vector< double,std::allocator< double > > > > > > const &,std::vector< std::vector< std::vector< int,std::allocator< int > >,std::allocator< std::vector< int,std::allocator< int > > > >,std::allocator< std::vector< std::vector< int,std::allocator< int > >,std::allocator< std::vector< int,std::allocator< int > > > > > > const &,std::vector< PathTrie *,std::allocator< PathTrie * > > &,std::vector< bool,std::allocator< bool > > const &,size_t,size_t,int)
    ctc_beam_search_decoder_batch(std::vector< std::vector< std::vector< double,std::allocator< double > >,std::allocator< std::vector< double,std::allocator< double > > > >,std::allocator< std::vector< std::vector< double,std::allocator< double > >,std::allocator< std::vector< double,std::allocator< double > > > > > > const &,std::vector< std::vector< std::vector< int,std::allocator< int > >,std::allocator< std::vector< int,std::allocator< int > > > >,std::allocator< std::vector< std::vector< int,std::allocator< int > >,std::allocator< std::vector< int,std::allocator< int > > > > > > const &,std::vector< PathTrie *,std::allocator< PathTrie * > > &,std::vector< bool,std::allocator< bool > > const &,size_t,size_t)


At:
  /root/.local/lib/python3.8/site-packages/swig_decoders.py(1645): ctc_beam_search_decoder_batch
  /ws/model_repo/wenet/1/wenet_onnx_model.py(193): batch_ctc_prefix_beam_search_cpu
  /ws/model_repo/wenet/1/wenet_onnx_model.py(127): infer
  /ws/model_repo/wenet/1/model.py(150): execute
```

 I tried to debug the docker in pycharm, but not find the crash reason yet. 
Can someone help?

**Comment by yuekaizhang** [comment]
> --audio_file=/ws/test_data/asrtest_xiangyu_0001.wav --model_name=streaming_wenet --streaming

![image](https://user-images.githubusercontent.com/28823245/220537511-5a62bb72-97e6-41a1-8d5e-ef4a4ff25733.png)

Sorry, I can't reproduce it with your wav file. The error is caused by your env or model_repo.
 
Which dockerfile are you used?  I am using this prebuilt image ```docker pull soar97/triton-wenet:22.12``` from https://github.com/wenet-e2e/wenet/blob/main/runtime/gpu/Dockerfile/Dockerfile.server.

If you docker is okay, you may try this model_repo https://huggingface.co/yuekai/triton_speech_recognition_benchmark/tree/main/model_repo_stateful_conformer_aishell2_wenet.

**Comment by duj12** [comment]
> > --audio_file=/ws/test_data/asrtest_xiangyu_0001.wav --model_name=streaming_wenet --streaming
> 
> ![image](https://user-images.githubusercontent.com/28823245/220537511-5a62bb72-97e6-41a1-8d5e-ef4a4ff25733.png)
> 
> Sorry, I can't reproduce it with your wav file. The error is caused by your env or model_repo.
> 
> Which dockerfile are you used? I am using this prebuilt image `docker pull soar97/triton-wenet:22.12` from https://github.com/wenet-e2e/wenet/blob/main/runtime/gpu/Dockerfile/Dockerfile.server.
> 
> If your docker is okay, you may try this model_repo https://huggingface.co/yuekai/triton_speech_recognition_benchmark/tree/main/model_repo_stateful_conformer_aishell2_wenet.

Thanks. I will check it with the offical image and model_repo later.
Maybe there is some thing wrong with my image env or model_repo.
