### ISSUE TITLE
runtime/openvino build failed

### ISSUE THREAD

**Issue by veelion** [wenet-e2e/wenet#1747]
1. cmake got the error:
```
CMake Error at ov/CMakeLists.txt:12 (find_package):
  By not providing "FindTBB.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "TBB", but
  CMake did not find one.
```
there is a config for TBB in `ov/CMakeLists.txt`:
```
set(TBB_DIR ${openvino_SOURCE_DIR}/runtime/3rdparty/tbb/cmake)
```
but, there is no 3rdparty dir.

so, I manually download `oneapi-tbb-2021.8.0` and put it in the right dir, cmake succeeded.

2. make compiled every c/c++ file successfully, but ld met the error:
```
[ 83%] Linking CXX executable label_checker_main                                                                                                                                     
/usr/bin/ld: warning: libpugixml.so.1, needed by ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libtbb.so.2, needed by ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0, not found (try using -rpath or -rpath-link)
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_document::load_string(char const*, unsigned int)'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_node::insert_child_after(char const*, pugi::xml_node const&)'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_node::next_sibling() const'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_node::offset_debug() const'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `tbb::task::note_affinity(unsigned short)'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `tbb::internal::allocate_via_handler_v3(unsigned long)'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_node::first_child() const'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_node::prepend_attribute(char const*)'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `tbb::interface7::internal::task_arena_base::internal_current_slot()'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_attribute::set_value(char const*)'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `tbb::internal::NFS_Allocate(unsigned long, unsigned long, void*)'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_node::empty() const'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `tbb::internal::NFS_Free(void*)'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_document::document_element() const'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `tbb::internal::allocate_continuation_proxy::allocate(unsigned long) const'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `tbb::internal::throw_exception_v4(tbb::internal::exception_id)'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_node::name() const'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `tbb::task_scheduler_init::terminate()'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_document::reset()'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `tbb::internal::concurrent_queue_base_v3::internal_pop_if_present(void*)'/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `tbb::interface7::internal::task_arena_base::internal_enqueue(tbb::task&, long) const'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `typeinfo for tbb::internal::concurrent_queue_base_v3'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_node::insert_move_after(pugi::xml_node const&, pugi::xml_node 
const&)'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `tbb::interface9::global_control::internal_create()'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `tbb::internal::concurrent_queue_base_v3::concurrent_queue_base_v3(unsigned long)'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_node::append_child(char const*)'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_node_iterator::operator*() const'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `typeinfo for tbb::task'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_node::append_child(pugi::xml_node_type)'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `tbb::interface9::global_control::internal_destroy()'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_attribute::set_value(long long)'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_node::child(char const*) const'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `tbb::internal::concurrent_vector_base_v3::~concurrent_vector_base_v3()'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `tbb::interface7::internal::task_arena_base::internal_terminate()'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_node_iterator::operator++()'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_parse_result::operator bool() const'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `tbb::internal::concurrent_vector_base_v3::internal_clear(void (*)(void*, unsigned long))'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_node::end() const'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `tbb::internal::deallocate_via_handler_v3(void*)'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `tbb::internal::allocate_root_with_context_proxy::free(tbb::task&) const'/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `tbb::task_group_context::init()'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_parse_result::description() const'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_node::prepend_move(pugi::xml_node const&)'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_node::operator void (*)(pugi::xml_node***)() const'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `tbb::internal::thread_get_id_v3()'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_attribute::set_value(double)'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `tbb::internal::concurrent_queue_base_v3::internal_finish_clear()'       /usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `tbb::internal::task_scheduler_observer_v3::observe(bool)'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_node::attribute(char const*) const'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_attribute::empty() const'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_attribute::value() const'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_node::parent() const'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `tbb::internal::concurrent_queue_base_v3::internal_push_if_not_full(void 
const*)'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_document::xml_document()'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `tbb::interface7::internal::task_arena_base::internal_initialize()'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `tbb::internal::get_initial_auto_partitioner_divisor()'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `tbb::internal::concurrent_queue_base_v8::internal_push_move(void const*)'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_attribute::set_value(bool)'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `tbb::task_scheduler_init::initialize(int, unsigned long)'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `tbb::internal::concurrent_queue_base_v3::internal_pop(void*)'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_node::child_value() const'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_document::load_buffer(void const*, unsigned long, unsigned int, pugi::xml_encoding)'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_document::load_file(wchar_t const*, unsigned int, pugi::xml_encoding)'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_node::next_sibling(char const*) const'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_node::set_value(char const*)'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_node::operator!() const'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_attribute::set_value(unsigned long long)'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_attribute::set_value(int)'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_node::begin() const'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_node_iterator::operator!=(pugi::xml_node_iterator const&) const'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `tbb::task_group_context::~task_group_context()'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `tbb::internal::allocate_child_proxy::allocate(unsigned long) const'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_document::save(std::ostream&, char const*, unsigned int, pugi::xml_encoding) const'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `tbb::internal::concurrent_vector_base_v3::internal_grow_by(unsigned long, unsigned long, void (*)(void*, void const*, unsigned long), void const*)'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `tbb::interface7::internal::task_arena_base::internal_execute(tbb::interface7::internal::delegate_base&) const'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_attribute_iterator::operator==(pugi::xml_attribute_iterator const&) const'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_node::insert_child_before(char const*, pugi::xml_node const&)'/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_document::~xml_document()'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `tbb::internal::concurrent_queue_base_v3::~concurrent_queue_base_v3()'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `tbb::assertion_failure(char const*, int, char const*, char const*)'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_node::attributes() const'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_node::remove_child(pugi::xml_node const&)'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `tbb::internal::allocate_root_with_context_proxy::allocate(unsigned long) const'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_node::append_attribute(char const*)'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `tbb::interface7::internal::task_arena_base::internal_max_concurrency(tbb::interface7::task_arena const*)'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `pugi::xml_node::remove_attribute(char const*)'
/usr/bin/ld: ../../fc_base/openvino-src/runtime/lib/intel64/libopenvino.so.2022.3.0: undefined reference to `tbb::internal::concurrent_queue_base_v3::internal_set_capacity(long, unsigned long)'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/CMakeFiles/label_checker_main.dir/build.make:95: bin/label_checker_main] Error 1
make[1]: *** [CMakeFiles/Makefile2:2144: bin/CMakeFiles/label_checker_main.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```
Is there something wrong with `openai-tbb`? Please help me Thanks. @FionaZZ92

**Comment by FionaZZ92** [comment]
@veelion Our Linux runtime pkg does not provide TBB, you may install system TBB library by:
Ubuntu/Debian : sudo apt install libtbb-dev
CentOS: sudo yum install tbb-devel

The the tbb will installed in " /usr/lib/x86_64-linux-gnu/libtbb.so.2", then the ov library will link to system tbb lib. I will update the tbb installation method into readme file, thanks a lot.

**Comment by veelion** [comment]
OpenVINO™ runtime with Model Optimizer (MO) command tool for model conversion failed:
```
mo --input_model onnx/encoder.onnx --input chunk[1,-1,80],att_cache[12,4,-1,128],cnn_cache[12,1,256,7] --output_dir openvino 
[ ERROR ]  No node with name cnn_cache
```
remove cnn_cache and then:

```
mo --input_model onnx/encoder.onnx --input chunk[1,-1,80],att_cache[12,4,-1,128] --output_dir openvino 
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  While validating ONNX node '<Node(Concat): Concat_275>':
Check 'T::merge_into(output_shape, input)' failed at src/core/shape_inference/include/concat_shape_inference.hpp:37:
While validating node 'v0::Concat Concat_1127 (Split_274[0]:f32[1,4,?,64], Transpose_271[0]:f32[1,8,?,64]) -> (dynamic[...])' with friendly_name 'Concat_1127':
Argument shapes are inconsistent; they must have the same rank, and must have equal dimension everywhere except on the concatenation axis (axis 2).

[ ERROR ]  Traceback (most recent call last):
  File "~/miniconda3/lib/python3.8/site-packages/openvino/tools/mo/main.py", line 50, in main
    ngraph_function = convert_model(**argv)
  File "~/miniconda3/lib/python3.8/site-packages/openvino/tools/mo/convert.py", line 47, in convert_model
    return _convert(**args)
  File "~/miniconda3/lib/python3.8/site-packages/openvino/tools/mo/convert_impl.py", line 937, in _convert
    raise e.with_traceback(None)
RuntimeError: While validating ONNX node '<Node(Concat): Concat_275>':
Check 'T::merge_into(output_shape, input)' failed at src/core/shape_inference/include/concat_shape_inference.hpp:37:
While validating node 'v0::Concat Concat_1127 (Split_274[0]:f32[1,4,?,64], Transpose_271[0]:f32[1,8,?,64]) -> (dynamic[...])' with friendly_name 'Concat_1127':
Argument shapes are inconsistent; they must have the same rank, and must have equal dimension everywhere except on the concatenation axis (axis 2).


[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------

**Comment by veelion** [comment]
change att_cache to `att_cache[12,8,-1,128]` makes it success.

**Comment by veelion** [comment]
> change att_cache to `att_cache[12,8,-1,128]` makes it success.

Note: the shape of `--input` for `mo` should match your model.

**Comment by veelion** [comment]
inference failed:
```
E0315 10:38:38.542884 3086255 ov_asr_model.cc:177] error when load OV model r_cnn_cache has zero dimension which is not allowed
```

**Comment by veelion** [comment]
> inference failed:
> 
> ```
> E0315 10:38:38.542884 3086255 ov_asr_model.cc:177] error when load OV model r_cnn_cache has zero dimension which is not allowed
> ```

@FionaZZ92 Would you like to give me some suggestion on `mo` convertion and the inference error? Thanks.

**Comment by FionaZZ92** [comment]
@veelion  I am using pretrained model from https://github.com/wenet-e2e/wenet/blob/main/docs/pretrained_models.md as an example for model conversion. If you have own model, need to align the shape and name of inputs of your model. I am not sure if you are able to share onnx model with me, I can help to check the proper inputs you should use for your model.

**Comment by veelion** [comment]
The pretrained model may be for both offline and online decoding, but mine is only for offline, and I found there are difference between the two model's onnx model. Thank you very much.

**Comment by Yymax-max** [comment]
i apt install libtbb-dev
alse meet CMake Error at ov/CMakeLists.txt:12 (find_package):
  By not providing "FindTBB.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "TBB", but
  CMake did not find one.

  Could not find a package configuration file provided by "TBB" with any of
  the following names:

    TBBConfig.cmake
    tbb-config.cmake

  Add the installation prefix of "TBB" to CMAKE_PREFIX_PATH or set "TBB_DIR"
  to a directory containing one of the above files.  If "TBB" provides a
  separate development package or SDK, be sure it has been installed.
how can i do

**Comment by Yymax-max** [comment]
can support gpu  infer ？@FionaZZ92

**Comment by FionaZZ92** [comment]
> 

Currently not able to infer with Intel GPU. We are working on model engagement.

**Comment by Yymax-max** [comment]
> Currently not able to infer with Intel GPU. We are working on model engagement.

ok，thanks

**Comment by WangGewu** [comment]
> inference failed:
> 
> ```
> E0315 10:38:38.542884 3086255 ov_asr_model.cc:177] error when load OV model r_cnn_cache has zero dimension which is not allowed
> ```

can you tell me how to solve this problem?

**Comment by Yymax-max** [comment]
openvino window端可以支持编译吗
