### ISSUE TITLE
Problem about training  environment

### ISSUE THREAD

**Issue by dospeech** [wenet-e2e/wenet#1855]
Hello, when i run the training script,I have this problem,can you  help me? what should i do? Thanks!!!

./run.sh: init method is file://
total gpus is: 8
2023-05-17 22:45:32,061 INFO training on multiple gpus, this gpu 7
2023-05-17 22:45:32,061 INFO training on multiple gpus, this gpu 6
2023-05-17 22:45:32,061 INFO training on multiple gpus, this gpu 0
2023-05-17 22:45:32,061 INFO training on multiple gpus, this gpu 2
2023-05-17 22:45:32,061 INFO training on multiple gpus, this gpu 5
2023-05-17 22:45:32,061 INFO training on multiple gpus, this gpu 1
2023-05-17 22:45:32,061 INFO training on multiple gpus, this gpu 3
2023-05-17 22:45:32,061 INFO training on multiple gpus, this gpu 4
Traceback (most recent call last):
  File "wenet/bin/train.py", line 309, in <module>
    main()
  File "wenet/bin/train.py", line 141, in main
    dist.init_process_group(args.dist_backend,
  File "/mnt/miniconda/envs/wenet/lib/python3.8/site-packages/torch/distributed/
distributed_c10d.py", line 576, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/mnt/miniconda/envs/wenet/lib/python3.8/site-packages/torch/distributed/
rendezvous.py", line 112, in _file_rendezvous_handler
    raise _error("path missing")
ValueError: Error initializing torch.distributed using file:// rendezvous: path missing

**Comment by robin1001** [comment]
Make sure you do not delete the following variable.


![image](https://github.com/wenet-e2e/wenet/assets/6036624/7b5e424c-e3b6-4d5b-88f1-3456067a9c56)
