### ISSUE TITLE
Paraformer: different dimension of tensors

### ISSUE THREAD

**Issue by egorsmkv** [wenet-e2e/wenet#1871]
**Describe the bug**

I am testing Paraformer architecture and got this traceback during model testing:

```
Traceback (most recent call last):
  File "/root/wenet-2.2.1/examples/csv/paraformer/wenet/bin/recognize.py", line 385, in <module>
    main()
  File "/root/wenet-2.2.1/examples/csv/paraformer/wenet/bin/recognize.py", line 366, in main
    hyps = model.paraformer_greedy_search(
  File "/root/wenet-2.2.1/wenet/paraformer/paraformer.py", line 210, in paraformer_greedy_search
    predictor_outs = self.calc_predictor(encoder_out, encoder_mask)
  File "/root/wenet-2.2.1/wenet/paraformer/paraformer.py", line 156, in calc_predictor
    self.predictor(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/wenet-2.2.1/wenet/cif/predictor.py", line 75, in forward
    hidden, alphas, token_num = self.tail_process_fn(hidden, alphas,
  File "/root/wenet-2.2.1/wenet/cif/predictor.py", line 96, in tail_process_fn
    mask_1 = torch.cat([mask, zeros_t], dim=1)
RuntimeError: Tensors must have same number of dimensions: got 5 and 2
```

**To Reproduce**
1. Train a Paraformer model
2. Star evaluation

**Additional context**

wenet - 2.2.1
pytorch - 1.13.1
python - 3.10

**Comment by MrSupW** [comment]
Thanks for your feedback. I would like to ask what dataset you are using?

**Comment by egorsmkv** [comment]
Hello! Any update on the issue?

**Comment by y00281951** [comment]
i meet the same problem.
test dataset is aishell1-test

**Comment by lxp3** [comment]
There are some mistakes of the naming of two variables in [here](https://github.com/wenet-e2e/wenet/blob/main/wenet/paraformer/paraformer.py), i.e., 'encoder_mask' and 'encoder_out_lens'. We coud fix it by referring to the original implementation [funasr](https://github.com/alibaba-damo-academy/FunASR/blob/main/funasr/models/e2e_asr_paraformer.py).
`
In wenet/paraformer/paraformer.py, you need following change: 

false: 
    predictor_outs = self.calc_predictor(encoder_out, encoder_mask)
true: 
    predictor_outs = self.calc_predictor(encoder_out, encoder_out_lens)

false:
    def calc_predictor(self, encoder_out, encoder_out_lens):

        encoder_mask = (~make_pad_mask(
            encoder_out_lens, max_len=encoder_out.size(1))[:, None, :]).to(
                encoder_out.device)

true:
    def calc_predictor(self, encoder_out, encoder_mask):

        encoder_mask = (~make_pad_mask(
            encoder_mask, max_len=encoder_out.size(1))[:, None, :]).to(
                encoder_out.device)

false:
        decoder_outs = self.cal_decoder_with_predictor(encoder_out,
                                                       encoder_out_lens,
                                                       pre_acoustic_embeds,
                                                       pre_token_length)
true:
        decoder_outs = self.cal_decoder_with_predictor(encoder_out,                                                                                                           
                                                       encoder_mask,
                                                       pre_acoustic_embeds,
                                                       pre_token_length)
false:
    def cal_decoder_with_predictor(self, encoder_out, encoder_out_lens,
                                   sematic_embeds, ys_pad_lens):

true:
    def cal_decoder_with_predictor(self, encoder_out, encoder_mask,                                                                                                           
                                   sematic_embeds, ys_pad_lens):
`
By doing this, it's work for me to do the paraformer_greedy_search decoding on aishell-1 testset.

**Comment by egorsmkv** [comment]
@lxp3 I have patched my fork and got one exception only during inference:

```
2023-06-27 16:31:02,536 INFO Checkpoint: loading from checkpoint exp/conformer/avg_6.pt for GPU
2023-06-27 16:31:02,536 INFO Checkpoint: loading from checkpoint exp/conformer/avg_6.pt for GPU
2023-06-27 16:31:12,168 INFO 1122 ▁▁▁▁▁
Traceback (most recent call last):
  File "/root/wenet-2.2.1/examples/csv/paraformer/wenet/bin/recognize.py", line 385, in <module>
    main()
  File "/root/wenet-2.2.1/examples/csv/paraformer/wenet/bin/recognize.py", line 358, in main
    hyps = model.paraformer_beam_search(
  File "/root/wenet-2.2.1/wenet/paraformer/paraformer.py", line 292, in paraformer_beam_search
    predictor_outs = self.calc_predictor(encoder_out, encoder_mask)
  File "/root/wenet-2.2.1/wenet/paraformer/paraformer.py", line 156, in calc_predictor
    self.predictor(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/wenet-2.2.1/wenet/cif/predictor.py", line 75, in forward
    hidden, alphas, token_num = self.tail_process_fn(hidden, alphas,
  File "/root/wenet-2.2.1/wenet/cif/predictor.py", line 96, in tail_process_fn
    mask_1 = torch.cat([mask, zeros_t], dim=1)
RuntimeError: Tensors must have same number of dimensions: got 5 and 2
```

**Comment by lxp3** [comment]
@egorsmkv  It's supposed to use the 'encoder_out_lens' as input  instead of 'encoder_mask' when calling the self.calc_predictor().
`predictor_outs = self.calc_predictor(encoder_out, encoder_out_lens)`

**Comment by egorsmkv** [comment]
@lxp3 now I am getting another exception:

```
Traceback (most recent call last):
  File "/root/wenet-2.2.1/examples/csv/paraformer/wenet/bin/recognize.py", line 385, in <module>
    main()
  File "/root/wenet-2.2.1/examples/csv/paraformer/wenet/bin/recognize.py", line 358, in main
    hyps = model.paraformer_beam_search(
  File "/root/wenet-2.2.1/wenet/paraformer/paraformer.py", line 300, in paraformer_beam_search
    decoder_outs = self.cal_decoder_with_predictor(encoder_out,
  File "/root/wenet-2.2.1/wenet/paraformer/paraformer.py", line 165, in cal_decoder_with_predictor
    decoder_out, _, _ = self.decoder(encoder_out, encoder_mask,
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/wenet-2.2.1/wenet/transformer/decoder.py", line 136, in forward
    x, tgt_mask, memory, memory_mask = layer(x, tgt_mask, memory,
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/wenet-2.2.1/wenet/transformer/decoder_layer.py", line 118, in forward
    self.src_attn(x, memory, memory, memory_mask)[0])
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/wenet-2.2.1/wenet/transformer/attention.py", line 186, in forward
    return self.forward_attention(v, scores, mask), new_cache
  File "/root/wenet-2.2.1/wenet/transformer/attention.py", line 101, in forward_attention
    if mask.size(2) > 0 :  # time2 > 0
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 2)
```

**Comment by egorsmkv** [comment]
@lxp3 thanks! Now it works.
