### ISSUE TITLE
RuntimeError: locale::facet::_S_create_c_locale name not valid

### ISSUE THREAD

**Issue by yyz845935161** [wenet-e2e/wenet#1886]
当我使用

wav_file = "010000_16.wav"
decoder = wenet.Decoder(lang='chs')
ans = decoder.decode_wav(wav_file)

print(ans)
这个代码时，出现这个错误
Traceback (most recent call last):
  File "/home/dataset/yyz/wespeaker/wenet.py", line 30, in <module>
    ans = decoder.decode_wav(wav_file)
  File "/home/dataset/miniconda3/envs/wenet/lib/python3.8/site-packages/wenetruntime/decoder.py", line 114, in decode_wav
    return self.decode(wav, True)
  File "/home/dataset/miniconda3/envs/wenet/lib/python3.8/site-packages/wenetruntime/decoder.py", line 96, in decode
    _wenet.wenet_decode(self.d, pcm, len(pcm), finish)
RuntimeError: locale::facet::_S_create_c_locale name not valid

**Comment by xingchensong** [comment]
请参考：
1. https://blog.csdn.net/CSDN330/article/details/104926729
2. https://stackoverflow.com/questions/26324209/understanding-locale-class-localefacet-s-create-c-locale-name-not-valid
