### ISSUE TITLE
get error while build binding python on windows

### ISSUE THREAD

**Issue by kli017** [wenet-e2e/wenet#1900]
While I was Building on Local Machine (Win11)
cd wenet/runtime/binding/python
python setup.py install 

I get bellow error
`running install
running bdist_egg
running egg_info
writing wenetruntime.egg-info\PKG-INFO
writing dependency_links to wenetruntime.egg-info\dependency_links.txt
writing requirements to wenetruntime.egg-info\requires.txt
writing top-level names to wenetruntime.egg-info\top_level.txt
reading manifest file 'wenetruntime.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'wenetruntime.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
Setting PYTHON_EXECUTABLE to D:\Anaconda\envs\wenetruntime\python.exe
-- Building for: NMake Makefiles
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:3 (project):
  The CMAKE_C_COMPILER:

    cl

  is not a full path and was not found in the PATH.

  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.

CMake Error at CMakeLists.txt:3 (project):
  The CMAKE_CXX_COMPILER:

    cl

  is not a full path and was not found in the PATH.

  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "G:/wenet/runtime/binding/python/build/temp.win-amd64-3.6/Release/CMakeFiles/CMakeOutput.log".
See also "G:/wenet/runtime/binding/python/build/temp.win-amd64-3.6/Release/CMakeFiles/CMakeError.log".
系统找不到指定的文件。
CMake Error: Generator: execution of make failed. Make command was: nmake /nologo _wenet &&
Traceback (most recent call last):
  File "setup.py", line 90, in <module>
    license="Apache licensed, as found in the LICENSE file",
  File "D:\Anaconda\envs\wenetruntime\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "D:\Anaconda\envs\wenetruntime\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\Anaconda\envs\wenetruntime\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "D:\Anaconda\envs\wenetruntime\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Anaconda\envs\wenetruntime\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "D:\Anaconda\envs\wenetruntime\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "D:\Anaconda\envs\wenetruntime\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Anaconda\envs\wenetruntime\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Anaconda\envs\wenetruntime\lib\site-packages\setuptools\command\bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "D:\Anaconda\envs\wenetruntime\lib\site-packages\setuptools\command\bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "D:\Anaconda\envs\wenetruntime\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Anaconda\envs\wenetruntime\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Anaconda\envs\wenetruntime\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "D:\Anaconda\envs\wenetruntime\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "D:\Anaconda\envs\wenetruntime\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Anaconda\envs\wenetruntime\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Anaconda\envs\wenetruntime\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "D:\Anaconda\envs\wenetruntime\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "D:\Anaconda\envs\wenetruntime\lib\distutils\command\build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "D:\Anaconda\envs\wenetruntime\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "setup.py", line 38, in build_extension
    "\nBuild wenet failed. Please check the error message.\n"
Exception:
Build wenet failed. Please check the error message.`

**Comment by kli017** [comment]
python vesiron is 3.6.13

**Comment by kli017** [comment]
after setting the C and CXX compiler finally get another error

`Determining if the C compiler works failed with the following output:
Change Dir: G:/wenet/runtime/binding/python/build/temp.win-amd64-3.6/Release/CMakeFiles/CMakeTmp

Run Build Command(s):nmake /nologo cmTC_7d98e\fast && 	"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\Hostx64\x64\nmake.exe" -f CMakeFiles\cmTC_7d98e.dir\build.make /nologo -L                  CMakeFiles\cmTC_7d98e.dir\build
Building C object CMakeFiles/cmTC_7d98e.dir/testCCompiler.c.obj
	C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1436~1.325\bin\Hostx64\x64\cl.exe @C:\Users\admin\AppData\Local\Temp\nm6A99.tmp
testCCompiler.c
Linking C executable cmTC_7d98e.exe
	D:\cmake-3.17.0-win64-x64\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_7d98e.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests  -- C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1436~1.325\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\cmTC_7d98e.dir\objects1.rsp @C:\Users\admin\AppData\Local\Temp\nm6AD9.tmp
RC Pass 1: command "rc /fo CMakeFiles\cmTC_7d98e.dir/manifest.res CMakeFiles\cmTC_7d98e.dir/manifest.rc" failed (exit code 0) with the following output:
系统找不到指定的文件。NMAKE : fatal error U1077: “D:\cmake-3.17.0-win64-x64\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_7d98e.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests  -- C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1436~1.325\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\cmTC_7d98e.dir\objects1.rsp @C:\Users\admin\AppData\Local\Temp\nm6AD9.tmp”: 返回代码“0xffffffff”
Stop.
NMAKE : fatal error U1077: “"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\Hostx64\x64\nmake.exe" -f CMakeFiles\cmTC_7d98e.dir\build.make /nologo -L                  CMakeFiles\cmTC_7d98e.dir\build”: 返回代码“0x2”
Stop.`
