### ISSUE TITLE
'cmake' 不是内部或外部命令，也不是可运行的程序

### ISSUE THREAD

**Issue by roundXin** [wenet-e2e/wenet#1930]
running bdist_egg
running egg_info
writing wenetruntime.egg-info\PKG-INFO
writing dependency_links to wenetruntime.egg-info\dependency_links.txt
writing requirements to wenetruntime.egg-info\requires.txt
writing top-level names to wenetruntime.egg-info\top_level.txt
reading manifest file 'wenetruntime.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'wenetruntime.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
Setting PYTHON_EXECUTABLE to D:\lvsiqin\common\APPlist\Miniconda3\APP\envs\RowChat\python.exe
'cmake' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'cmake' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Traceback (most recent call last):
  File "setup.py", line 66, in <module>
    setuptools.setup(
  File "D:\lvsiqin\common\APPlist\Miniconda3\APP\envs\RowChat\lib\site-packages\setuptools\__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "D:\lvsiqin\common\APPlist\Miniconda3\APP\envs\RowChat\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "D:\lvsiqin\common\APPlist\Miniconda3\APP\envs\RowChat\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "D:\lvsiqin\common\APPlist\Miniconda3\APP\envs\RowChat\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "D:\lvsiqin\common\APPlist\Miniconda3\APP\envs\RowChat\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "D:\lvsiqin\common\APPlist\Miniconda3\APP\envs\RowChat\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\lvsiqin\common\APPlist\Miniconda3\APP\envs\RowChat\lib\site-packages\setuptools\command\install.py", line 74, in run
    self.do_egg_install()
  File "D:\lvsiqin\common\APPlist\Miniconda3\APP\envs\RowChat\lib\site-packages\setuptools\command\install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "D:\lvsiqin\common\APPlist\Miniconda3\APP\envs\RowChat\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "D:\lvsiqin\common\APPlist\Miniconda3\APP\envs\RowChat\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "D:\lvsiqin\common\APPlist\Miniconda3\APP\envs\RowChat\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\lvsiqin\common\APPlist\Miniconda3\APP\envs\RowChat\lib\site-packages\setuptools\command\bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "D:\lvsiqin\common\APPlist\Miniconda3\APP\envs\RowChat\lib\site-packages\setuptools\command\bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "D:\lvsiqin\common\APPlist\Miniconda3\APP\envs\RowChat\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "D:\lvsiqin\common\APPlist\Miniconda3\APP\envs\RowChat\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "D:\lvsiqin\common\APPlist\Miniconda3\APP\envs\RowChat\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\lvsiqin\common\APPlist\Miniconda3\APP\envs\RowChat\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "D:\lvsiqin\common\APPlist\Miniconda3\APP\envs\RowChat\lib\site-packages\setuptools\_distutils\command\install_lib.py", line 112, in build
    self.run_command('build_ext')
  File "D:\lvsiqin\common\APPlist\Miniconda3\APP\envs\RowChat\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "D:\lvsiqin\common\APPlist\Miniconda3\APP\envs\RowChat\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "D:\lvsiqin\common\APPlist\Miniconda3\APP\envs\RowChat\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\lvsiqin\common\APPlist\Miniconda3\APP\envs\RowChat\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
    _build_ext.run(self)
  File "D:\lvsiqin\common\APPlist\Miniconda3\APP\envs\RowChat\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
    self.build_extensions()
  File "D:\lvsiqin\common\APPlist\Miniconda3\APP\envs\RowChat\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 468, in build_extensions
    self._build_extensions_serial()
  File "D:\lvsiqin\common\APPlist\Miniconda3\APP\envs\RowChat\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 494, in _build_extensions_serial
    self.build_extension(ext)
  File "setup.py", line 37, in build_extension
    raise Exception(
Exception:
Build wenet failed. Please check the error message.
You can ask for help by creating an issue on GitHub.

Click:
    https://github.com/wenet-e2e/wenet/issues/new

**Comment by pengzhendong** [comment]
请安装 cmake 并且填加到环境变量。
