### ISSUE TITLE
Tutorial on AIShell 第四步训练神经网络报错

### ISSUE THREAD

**Issue by didi222-lqq** [wenet-e2e/wenet#2026]
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
wenet/bin/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-09-25_10:56:59
  host      : g0030.para.ai
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 11606)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2023-09-25_10:56:59
  host      : g0030.para.ai
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 11607)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2023-09-25_10:56:59
  host      : g0030.para.ai
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 11608)
  error_file: <N/A>

以上是训练后产生的.out文件里的报错内容，请问哪个地方出错了

**Comment by cdliang11** [comment]
这好像看不出来，有更详细的报错信息吗

**Comment by didi222-lqq** [comment]
/var/spool/slurmd/job777801/slurm_script: init method is file:///data/run01/scz0arv/lindaodi/wenet/examples/aishell/s0/exp/conformer/ddp_init
using torch ddp
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
[2023-09-25 10:56:27,063] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-09-25 10:56:27,063] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-09-25 10:56:27,063] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-09-25 10:56:27,063] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-09-25 10:56:27,063] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-09-25 10:56:27,063] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-09-25 10:56:27,063] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-09-25 10:56:27,063] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Failed to import k2         Notice that they are necessary for         k2 rnnt loss training
Failed to import k2         Notice that they are necessary for         k2 rnnt loss training
Failed to import k2         Notice that they are necessary for         k2 rnnt loss training
Failed to import k2         Notice that they are necessary for         k2 rnnt loss training
Failed to import k2         Notice that they are necessary for         k2 rnnt loss training
Failed to import k2         Notice that they are necessary for         k2 rnnt loss training
Failed to import k2         Notice that they are necessary for         k2 rnnt loss training
Failed to import k2         Notice that they are necessary for         k2 rnnt loss training
Warning: Failed to import k2 & icefall, which are for LF-MMI/hlg
Warning: Failed to import k2 & icefall, which are for LF-MMI/hlg
Warning: Failed to import k2 & icefall, which are for LF-MMI/hlg
Warning: Failed to import k2 & icefall, which are for LF-MMI/hlg
Warning: Failed to import k2 & icefall, which are for LF-MMI/hlg
Warning: Failed to import k2 & icefall, which are for LF-MMI/hlg
Warning: Failed to import k2 & icefall, which are for LF-MMI/hlg
Warning: Failed to import k2 & icefall, which are for LF-MMI/hlg
/HOME/scz0arv/.conda/envs/wenet/lib/python3.8/site-packages/torch/_jit_internal.py:726: FutureWarning: ignore(True) has been deprecated. TorchScript will now drop the function call on compilation. Use torch.jit.unused now. {}
  warnings.warn(
/HOME/scz0arv/.conda/envs/wenet/lib/python3.8/site-packages/torch/_jit_internal.py:726: FutureWarning: ignore(True) has been deprecated. TorchScript will now drop the function call on compilation. Use torch.jit.unused now. {}
  warnings.warn(
/HOME/scz0arv/.conda/envs/wenet/lib/python3.8/site-packages/torch/_jit_internal.py:726: FutureWarning: ignore(True) has been deprecated. TorchScript will now drop the function call on compilation. Use torch.jit.unused now. {}
  warnings.warn(
/HOME/scz0arv/.conda/envs/wenet/lib/python3.8/site-packages/torch/_jit_internal.py:726: FutureWarning: ignore(True) has been deprecated. TorchScript will now drop the function call on compilation. Use torch.jit.unused now. {}
  warnings.warn(
/HOME/scz0arv/.conda/envs/wenet/lib/python3.8/site-packages/torch/_jit_internal.py:726: FutureWarning: ignore(True) has been deprecated. TorchScript will now drop the function call on compilation. Use torch.jit.unused now. {}
  warnings.warn(
/HOME/scz0arv/.conda/envs/wenet/lib/python3.8/site-packages/torch/_jit_internal.py:726: FutureWarning: ignore(True) has been deprecated. TorchScript will now drop the function call on compilation. Use torch.jit.unused now. {}
  warnings.warn(
/HOME/scz0arv/.conda/envs/wenet/lib/python3.8/site-packages/torch/_jit_internal.py:726: FutureWarning: ignore(True) has been deprecated. TorchScript will now drop the function call on compilation. Use torch.jit.unused now. {}
  warnings.warn(
/HOME/scz0arv/.conda/envs/wenet/lib/python3.8/site-packages/torch/_jit_internal.py:726: FutureWarning: ignore(True) has been deprecated. TorchScript will now drop the function call on compilation. Use torch.jit.unused now. {}
  warnings.warn(
Traceback (most recent call last):
  File "wenet/bin/train.py", line 43, in <module>
    from wenet.utils.init_model import init_model
  File "/data/run01/scz0arv/lindaodi/wenet/wenet/utils/init_model.py", line 29, in <module>
Traceback (most recent call last):
  File "wenet/bin/train.py", line 43, in <module>
    from wenet.paraformer.paraformer import Paraformer
  File "/data/run01/scz0arv/lindaodi/wenet/wenet/paraformer/paraformer.py", line 23, in <module>
    from wenet.utils.init_model import init_model
  File "/data/run01/scz0arv/lindaodi/wenet/wenet/utils/init_model.py", line 29, in <module>
    from wenet.paraformer.search.beam_search import Hypothesis
  File "/data/run01/scz0arv/lindaodi/wenet/wenet/paraformer/search/beam_search.py", line 25, in <module>
    from wenet.paraformer.paraformer import Paraformer
  File "/data/run01/scz0arv/lindaodi/wenet/wenet/paraformer/paraformer.py", line 23, in <module>
Traceback (most recent call last):
  File "wenet/bin/train.py", line 43, in <module>
    from wenet.paraformer.utils import end_detect
  File "/data/run01/scz0arv/lindaodi/wenet/wenet/paraformer/utils.py", line 18, in <module>
    from wenet.paraformer.search.beam_search import Hypothesis
  File "/data/run01/scz0arv/lindaodi/wenet/wenet/paraformer/search/beam_search.py", line 25, in <module>
    from wenet.utils.init_model import init_model
  File "/data/run01/scz0arv/lindaodi/wenet/wenet/utils/init_model.py", line 29, in <module>
    import six
ModuleNotFoundError: No module named 'six'
    from wenet.paraformer.utils import end_detect
  File "/data/run01/scz0arv/lindaodi/wenet/wenet/paraformer/utils.py", line 18, in <module>
Traceback (most recent call last):
  File "wenet/bin/train.py", line 43, in <module>
    from wenet.paraformer.paraformer import Paraformer
  File "/data/run01/scz0arv/lindaodi/wenet/wenet/paraformer/paraformer.py", line 23, in <module>
    import six
ModuleNotFoundError: No module named 'six'
    from wenet.utils.init_model import init_model
  File "/data/run01/scz0arv/lindaodi/wenet/wenet/utils/init_model.py", line 29, in <module>
    from wenet.paraformer.search.beam_search import Hypothesis
  File "/data/run01/scz0arv/lindaodi/wenet/wenet/paraformer/search/beam_search.py", line 25, in <module>
Traceback (most recent call last):
  File "wenet/bin/train.py", line 43, in <module>
    from wenet.paraformer.paraformer import Paraformer
  File "/data/run01/scz0arv/lindaodi/wenet/wenet/paraformer/paraformer.py", line 23, in <module>
    from wenet.paraformer.utils import end_detect
  File "/data/run01/scz0arv/lindaodi/wenet/wenet/paraformer/utils.py", line 18, in <module>
    from wenet.utils.init_model import init_model
  File "/data/run01/scz0arv/lindaodi/wenet/wenet/utils/init_model.py", line 29, in <module>
    from wenet.paraformer.search.beam_search import Hypothesis
  File "/data/run01/scz0arv/lindaodi/wenet/wenet/paraformer/search/beam_search.py", line 25, in <module>
    import six
Traceback (most recent call last):
ModuleNotFoundError  File "wenet/bin/train.py", line 43, in <module>
    : from wenet.paraformer.paraformer import ParaformerNo module named 'six'

  File "/data/run01/scz0arv/lindaodi/wenet/wenet/paraformer/paraformer.py", line 23, in <module>
    from wenet.paraformer.utils import end_detect
  File "/data/run01/scz0arv/lindaodi/wenet/wenet/paraformer/utils.py", line 18, in <module>
    from wenet.paraformer.search.beam_search import Hypothesis
  File "/data/run01/scz0arv/lindaodi/wenet/wenet/paraformer/search/beam_search.py", line 25, in <module>
    from wenet.utils.init_model import init_model
  File "/data/run01/scz0arv/lindaodi/wenet/wenet/utils/init_model.py", line 29, in <module>
    import six
ModuleNotFoundError: No module named 'six'
Traceback (most recent call last):
  File "wenet/bin/train.py", line 43, in <module>
    from wenet.paraformer.utils import end_detect
  File "/data/run01/scz0arv/lindaodi/wenet/wenet/paraformer/utils.py", line 18, in <module>
    from wenet.paraformer.paraformer import Paraformer
  File "/data/run01/scz0arv/lindaodi/wenet/wenet/paraformer/paraformer.py", line 23, in <module>
    from wenet.utils.init_model import init_model
  File "/data/run01/scz0arv/lindaodi/wenet/wenet/utils/init_model.py", line 29, in <module>
    import six
ModuleNotFoundError: No module named 'six'
    from wenet.paraformer.search.beam_search import Hypothesis
  File "/data/run01/scz0arv/lindaodi/wenet/wenet/paraformer/search/beam_search.py", line 25, in <module>
Traceback (most recent call last):
  File "wenet/bin/train.py", line 43, in <module>
    from wenet.paraformer.paraformer import Paraformer
  File "/data/run01/scz0arv/lindaodi/wenet/wenet/paraformer/paraformer.py", line 23, in <module>
    from wenet.paraformer.utils import end_detect
  File "/data/run01/scz0arv/lindaodi/wenet/wenet/paraformer/utils.py", line 18, in <module>
    from wenet.utils.init_model import init_model
      File "/data/run01/scz0arv/lindaodi/wenet/wenet/utils/init_model.py", line 29, in <module>
from wenet.paraformer.search.beam_search import Hypothesis
  File "/data/run01/scz0arv/lindaodi/wenet/wenet/paraformer/search/beam_search.py", line 25, in <module>
    import six
ModuleNotFoundError: No module named 'six'
    from wenet.paraformer.paraformer import Paraformer    
from wenet.paraformer.utils import end_detect  File "/data/run01/scz0arv/lindaodi/wenet/wenet/paraformer/paraformer.py", line 23, in <module>

  File "/data/run01/scz0arv/lindaodi/wenet/wenet/paraformer/utils.py", line 18, in <module>
        import sixfrom wenet.paraformer.search.beam_search import Hypothesis

ModuleNotFoundError  File "/data/run01/scz0arv/lindaodi/wenet/wenet/paraformer/search/beam_search.py", line 25, in <module>
: No module named 'six'
    from wenet.paraformer.utils import end_detect
  File "/data/run01/scz0arv/lindaodi/wenet/wenet/paraformer/utils.py", line 18, in <module>
    import six
ModuleNotFoundError: No module named 'six'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 11605) of binary: /HOME/scz0arv/.conda/envs/wenet/bin/python
Traceback (most recent call last):
  File "/HOME/scz0arv/.conda/envs/wenet/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/HOME/scz0arv/.conda/envs/wenet/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/HOME/scz0arv/.conda/envs/wenet/lib/python3.8/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/HOME/scz0arv/.conda/envs/wenet/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/HOME/scz0arv/.conda/envs/wenet/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/HOME/scz0arv/.conda/envs/wenet/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
wenet/bin/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-09-25_10:56:59
  host      : g0030.para.ai
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 11606)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2023-09-25_10:56:59
  host      : g0030.para.ai
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 11607)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2023-09-25_10:56:59
  host      : g0030.para.ai
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 11608)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2023-09-25_10:56:59
  host      : g0030.para.ai
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 11609)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2023-09-25_10:56:59
  host      : g0030.para.ai
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 11610)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2023-09-25_10:56:59
  host      : g0030.para.ai
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 11611)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[7]:
  time      : 2023-09-25_10:56:59
  host      : g0030.para.ai
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 11612)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-25_10:56:59
  host      : g0030.para.ai
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 11605)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

这是完整的.out文件，麻烦您看看

> 这好像看不出来，有更详细的报错信息吗

**Comment by cdliang11** [comment]
> File "/data/run01/scz0arv/lindaodi/wenet/wenet/paraformer/paraformer.py", line 23, in
> import six
> ModuleNotFoundError: No module named 'six'

可能是这个原因

**Comment by didi222-lqq** [comment]
我导入这个包后重新训练，出现了以下问题：
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 5 (pid: 67123) of binary: /HOME/scz0arv/.conda/envs/wenet/bin/python
Traceback (most recent call last):
  File "/HOME/scz0arv/.conda/envs/wenet/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/HOME/scz0arv/.conda/envs/wenet/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/HOME/scz0arv/.conda/envs/wenet/lib/python3.8/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/HOME/scz0arv/.conda/envs/wenet/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/HOME/scz0arv/.conda/envs/wenet/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/HOME/scz0arv/.conda/envs/wenet/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

是不是我的cuda版本不一致呀，我下载的torch的cuda版本是11.6，但是nvcc -V出来的cuda版本是11.3
![image](https://github.com/wenet-e2e/wenet/assets/84363031/0e18162f-af46-46c1-8327-de095c1d6316)

![image](https://github.com/wenet-e2e/wenet/assets/84363031/3f349e3f-4bec-433d-a45e-cf407d187b57)

**Comment by didi222-lqq** [comment]
> > File "/data/run01/scz0arv/lindaodi/wenet/wenet/paraformer/paraformer.py", line 23, in
> > import six
> > ModuleNotFoundError: No module named 'six'
> 
> 可能是这个原因

我导入这个包后重新训练，出现了以下问题：
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 5 (pid: 67123) of binary: /HOME/scz0arv/.conda/envs/wenet/bin/python
Traceback (most recent call last):
  File "/HOME/scz0arv/.conda/envs/wenet/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/HOME/scz0arv/.conda/envs/wenet/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/HOME/scz0arv/.conda/envs/wenet/lib/python3.8/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/HOME/scz0arv/.conda/envs/wenet/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/HOME/scz0arv/.conda/envs/wenet/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/HOME/scz0arv/.conda/envs/wenet/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

是不是我的cuda版本不一致呀，我下载的torch的cuda版本是11.6，但是nvcc -V出来的cuda版本是11.3
![image](https://github.com/wenet-e2e/wenet/assets/84363031/0e18162f-af46-46c1-8327-de095c1d6316)

![image](https://github.com/wenet-e2e/wenet/assets/84363031/3f349e3f-4bec-433d-a45e-cf407d187b57)

**Comment by cdliang11** [comment]
可能是，更新下cuda版本

**Comment by didi222-lqq** [comment]
解决啦谢谢！
