### ISSUE TITLE
ImportError: DLL load failed while importing _wenet: 找不到指定的程序。

### ISSUE THREAD

**Issue by zth-1024** [wenet-e2e/wenet#2036]
Traceback (most recent call last):
  File "D:\PyCharm Projects\test\main.py", line 4, in <module>
    import wenetruntime as wenet
  File "D:\PyCharm Projects\test\venv\lib\site-packages\wenetruntime\__init__.py", line 1, in <module>
    from .decoder import Decoder  # noqa
  File "D:\PyCharm Projects\test\venv\lib\site-packages\wenetruntime\decoder.py", line 23, in <module>
    import _wenet
ImportError: DLL load failed while importing _wenet: 找不到指定的程序。

**Comment by Mddct** [comment]
can you show more info ：
windows version
python version
wenetruntime version

**Comment by zth-1024** [comment]
windows version：win10
python version:3.8
wenetruntime version:1.14.0
&nbsp;


Dream
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月9日(星期一) 上午9:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wenet-e2e/wenet] ImportError: DLL load failed while importing _wenet: 找不到指定的程序。 (Issue #2036)





 
can you show more info ：
 windows version
 python version
 wenetruntime version

**Comment by Mddct** [comment]
![6951696850747_ pic](https://github.com/wenet-e2e/wenet/assets/4906435/1765edce-5d27-4987-ba37-e186691e765d)
missing some lib？ WIll fix son。

**Comment by zth-1024** [comment]
Is it the problem with this package itself? Or am I using the wrong installation method？

**Comment by Mddct** [comment]
> Is it the problem with this package itself? Or am I using the wrong installation method？

package self。

**Comment by lingyuwangwang** [comment]
Hi，i also meet this problem. Can this problem only be solved in wsl? Can it not be executed in windows?

**Comment by zth-1024** [comment]
Now I can't execute it in Windows. But in Lunix it can.



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月19日(周四) 上午10:37
收件人: ***@***.***&gt;;
抄送: "Zhang ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [wenet-e2e/wenet] ImportError: DLL load failed while importing _wenet: 找不到指定的程序。 (Issue #2036)




 
Hi，i also meet this problem. Can this problem only be solved in wsl? Can it not be executed in windows?

**Comment by lingyuwangwang** [comment]
Thanks for you reply. Now it works on windows. i just use git clone https://github.com/wenet-e2e/wenet.git, and then install wenet.

**Comment by zth-1024** [comment]
You mean that clone wenet from github firstly and then use pip to install wenet module?发自我的手机-------- 原始邮件 --------发件人： wlyua ***@***.***>日期： 2023年10月19日周四 13:10收件人： wenet-e2e/wenet ***@***.***>抄送： Zhang Tonghui ***@***.***>, State change ***@***.***>主    题： Re: [wenet-e2e/wenet] ImportError: DLL load failed while importing _wenet: 找不到指定的程序。 (Issue #2036)
Thanks for you reply. Now it works on windows. i just use git clone https://github.com/wenet-e2e/wenet.git, and then install wenet.

**Comment by lingyuwangwang** [comment]
yes. just run these three lines of code in the terminal：
git clone https://github.com/wenet-e2e/wenet.git
cd wenet
pip install .
Then I can work on windows, i think we lost wenet model, so cant run on windows, but i dont know why it can works in linux without wenet. BTW pip3 install wenetruntime also need.

**Comment by zth-1024** [comment]
Thank you, I will try it later.发自我的手机-------- 原始邮件 --------发件人： wlyua ***@***.***>日期： 2023年10月20日周五 09:41收件人： wenet-e2e/wenet ***@***.***>抄送： Zhang Tonghui ***@***.***>, State change ***@***.***>主    题： Re: [wenet-e2e/wenet] ImportError: DLL load failed while importing _wenet: 找不到指定的程序。 (Issue #2036)
yes. just run these three lines of code in the terminal：
git clone https://github.com/wenet-e2e/wenet.git
cd wenet
pip install .
Then I can work on windows, i think we lost wenet model, so cant run on windows, but i dont know why it can works in linux without wenet. BTW pip3 install wenetruntime also need.
