### ISSUE TITLE
执行wenetruntime a_1.wav报错

### ISSUE THREAD

**Issue by Heavenbest** [wenet-e2e/wenet#2044]
**Describe the bug**

WARNING: Logging before InitGoogleLogging() is written to STDERR
I1011 10:52:43.620184 55956 wenet_api.cc:48] Reading torch model
Traceback (most recent call last):
  File "/data/pengshan/miniconda3/envs/torch-1.13/bin/wenetruntime", line 8, in <module>
    sys.exit(main())
  File "/data/pengshan/miniconda3/envs/torch-1.13/lib/python3.8/site-packages/wenetruntime/main.py", line 47, in main
    result = decoder.decode(args.audio)
  File "/data/pengshan/miniconda3/envs/torch-1.13/lib/python3.8/site-packages/wenetruntime/decoder.py", line 110, in decode
    data, _ = librosa.load(audio, sr=16000)
  File "/data/pengshan/miniconda3/envs/torch-1.13/lib/python3.8/site-packages/lazy_loader/__init__.py", line 78, in __getattr__
    attr = getattr(submod, name)
  File "/data/pengshan/miniconda3/envs/torch-1.13/lib/python3.8/site-packages/lazy_loader/__init__.py", line 77, in __getattr__
    submod = importlib.import_module(submod_path)
  File "/data/pengshan/miniconda3/envs/torch-1.13/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data/pengshan/miniconda3/envs/torch-1.13/lib/python3.8/site-packages/librosa-0.10.1-py3.8.egg/librosa/core/audio.py", line 32, in <module>
    resampy = lazy.load("resampy")
  File "/data/pengshan/miniconda3/envs/torch-1.13/lib/python3.8/site-packages/lazy_loader/__init__.py", line 208, in load
    loader = importlib.util.LazyLoader(spec.loader)
  File "/data/pengshan/miniconda3/envs/torch-1.13/lib/python3.8/importlib/util.py", line 282, in __init__
    self.__check_eager_loader(loader)
  File "/data/pengshan/miniconda3/envs/torch-1.13/lib/python3.8/importlib/util.py", line 273, in __check_eager_loader
    raise TypeError('loader must define exec_module()')
TypeError: loader must define exec_module()

**Desktop (please complete the following information):**
 - OS: ubuntu18.04
 python:3.8
torch:1.13
cuda:11.7

**Comment by xingchensong** [comment]
现在建议用cli方式，wenetruntime已经弃用
