### ISSUE TITLE
在训练aishell的stage5时，会报一个错误

### ISSUE THREAD

**Issue by zth-1024** [wenet-e2e/wenet#2150]
Traceback (most recent call last):
  File "wenet/bin/recognize.py", line 278, in <module>
    main()
  File "wenet/bin/recognize.py", line 254, in main
    results = model.decode(
  File "/data1/zhangtonghui/PyCharmProjects/wenet/wenet/transformer/asr_model.py", line 248, in decode
    results['attention_rescoring'] = attention_rescoring(
  File "/data1/zhangtonghui/PyCharmProjects/wenet/wenet/transformer/search.py", line 382, in attention_rescoring
    s = r_decoder_out[i][len(hyp) - j - 1][w]
IndexError: invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number

**Comment by zth-1024** [comment]
可能是直接git的项目还在修改的原因，使用2.2.1版本就不报错了
