### ISSUE TITLE
Trainning model with train_unified_conformer_ctl.yaml error

### ISSUE THREAD

**Issue by TicooLiu** [wenet-e2e/wenet#2269]
Trainning model with `train_unified_conformer_ctl.yaml` error.
We update source code at `2023-12-21`.
We trian model with `train_conformer.yaml` firstly, it is ok, we get the final model.
Then change `run.sh` as below:
```
#train_config=conf/train_conformer.yaml
#dir=exp/conformer
train_config=conf/train_unified_conformer_ctl.yaml
dir=exp/uni-conformer-ctl
```
We clean the train data in `./data` folder, and re-make it.
Re-train model with `run.sh` as stage seperate. 
From `stage 0` to `stage 3`, it is right, then to run `stage 4`, get error as below:
```
  traceback : Traceback (most recent call last):
    File "/home/ticoo/miniconda3/envs/wenet2/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
      return f(*args, **kwargs)
    File "wenet/bin/train.py", line 142, in main
      executor.train(model, optimizer, scheduler, train_data_loader,
    File "/home/ticoo/wenet/wenet/utils/executor.py", line 74, in train
      info_dict = batch_forward(model, batch_dict, scaler,
    File "/home/ticoo/wenet/wenet/utils/train_utils.py", line 464, in batch_forward
      loss_dict = model(batch, device)
    File "/home/ticoo/miniconda3/envs/wenet2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
      return forward_call(*input, **kwargs)
    File "/home/ticoo/miniconda3/envs/wenet2/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
      output = self._run_ddp_forward(*inputs, **kwargs)
    File "/home/ticoo/miniconda3/envs/wenet2/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1003, in _run_ddp_forward
      return module_to_run(*inputs, **kwargs)
    File "/home/ticoo/miniconda3/envs/wenet2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
      return forward_call(*input, **kwargs)
  TypeError: forward() missing 2 required positional arguments: 'text' and 'text_lengths'
```
It seems arguments loss, any advice???

**Comment by xingchensong** [comment]
Thx, this is a bug, please change the `forward()` in `ctl_model/*.py` according to https://github.com/wenet-e2e/wenet/pull/2242 

once u fix this issue, feel free to make a PR, we are happy to merge it.

**Comment by TicooLiu** [comment]
Thanks, got it.
