### ISSUE TITLE
About torchaudio

### ISSUE THREAD

**Issue by Mesteria** [wenet-e2e/wenet#2302]
I'm new in this area. When I run run.sh, it shows like this:

Traceback (most recent call last):
  File "tools/compute_cmvn_stats.py", line 11, in <module>
    import torchaudio
  File "/home/miniconda3/envs/wenet/lib/python3.8/site-packages/torchaudio/__init__.py", line 2, in <module>
    from torchaudio import (
  File "/home/miniconda3/envs/wenet/lib/python3.8/site-packages/torchaudio/pipelines/__init__.py", line 1, in <module>
    from ._wav2vec2 import (
ImportError: cannot import name 'Wav2Vec2Bundle' from 'torchaudio.pipelines._wav2vec2' (/home/miniconda3/envs/wenet/lib/python3.8/site-packages/torchaudio/pipelines/_wav2vec2/__init__.py)

I tried to solve it from Internet but I failed.

**Comment by Mesteria** [comment]
Please ignore the file run.sh, that's a file I wrote to use tools/compute_cmvn_stats.py.

**Comment by Mesteria** [comment]
I have solved that problem. The reason is that I haven't pip the required version. The requirement.txt contains what this project needs.
