### ISSUE TITLE
Something about decoding

### ISSUE THREAD

**Issue by Mesteria** [wenet-e2e/wenet#2319]
When I run recognize.py, an error rises like below:

Traceback (most recent call last):
  File "recognize.py", line 272, in <module>
    main()
  File "recognize.py", line 241, in main
    for batch_idx, batch in enumerate(test_data_loader):
  File "/home/miniconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/miniconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 671, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/miniconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 34, in fetch
    data.append(next(self.dataset_iter))
  File "/home/data/aizm/wenet/wenet/dataset/processor.py", line 641, in padding
    padded_wavs = pad_sequence(sorted_wavs,
  File "/home/miniconda3/envs/wenet/lib/python3.8/site-packages/torch/nn/utils/rnn.py", line 398, in pad_sequence
    return torch._C._nn.pad_sequence(sequences, batch_first, padding_value)
RuntimeError: The size of tensor a (109504) must match the size of tensor b (105008) at non-singleton dimension 1

But the first time I use it, there was no error like this. Is there anything I revised?

**Comment by Mesteria** [comment]
Today I change a video and it runs successfully. Is there anything requested I ignored?
