### ISSUE TITLE
audio.wav

### ISSUE THREAD

**Issue by si-hy** [wenet-e2e/wenet#2355]
Traceback (most recent call last):
  File "/home/imai/.local/bin/wenet", line 33, in <module>
    sys.exit(load_entry_point('wenet', 'console_scripts', 'wenet')())
  File "/home/imai/wenet/wenet/cli/transcribe.py", line 77, in main
    result = model.transcribe(args.audio_file, args.show_tokens_info)
  File "/home/imai/wenet/wenet/cli/model.py", line 132, in transcribe
    return self._decode(audio_file, tokens_info)
  File "/home/imai/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/imai/wenet/wenet/cli/model.py", line 81, in _decode
    feats = self.compute_feats(audio_file)
  File "/home/imai/wenet/wenet/cli/model.py", line 61, in compute_feats
    waveform, sample_rate = torchaudio.load(audio_file, normalize=False)
  File "/home/imai/.local/lib/python3.10/site-packages/torchaudio/_backend/utils.py", line 204, in load
    return backend.load(uri, frame_offset, num_frames, normalize, channels_first, format, buffer_size)
  File "/home/imai/.local/lib/python3.10/site-packages/torchaudio/_backend/ffmpeg.py", line 336, in load
    return load_audio(os.path.normpath(uri), frame_offset, num_frames, normalize, channels_first, format)
  File "/home/imai/.local/lib/python3.10/site-packages/torchaudio/_backend/ffmpeg.py", line 100, in load_audio
    return torch.ops.torchaudio.compat_load(src, format, filter, channels_first)
  File "/home/imai/.local/lib/python3.10/site-packages/torch/_ops.py", line 692, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: Failed to open the input "audio.wav" (No such file or directory).

When I put wenet --language english audio.wav in the terminal, that error occurs but I don't know how to fix it... Could I get help?

**Comment by Mddct** [comment]
plz check audio.wav filepath

**Comment by si-hy** [comment]
but there's no audio.wav filepath in my code file, then do I have to make it or is there a file that the creater made ?

**Comment by Mddct** [comment]
you need to use your audio file to decode

**Comment by si-hy** [comment]
oh ok, it works. Thx!
