### ISSUE TITLE
使用wenet在AISHELL-4数据集中报错

### ISSUE THREAD

**Issue by mjbgithubwork** [wenet-e2e/wenet#2464]
```
Traceback (most recent call last):
  File "local/aishell4_process_textgrid.py", line 107, in <module>
    main(args)
  File "local/aishell4_process_textgrid.py", line 47, in main
    tg = textgrid.TextGrid.fromFile(utt2textgrid[uttid])
  File "/data_disk/miniconda3/envs/wenet/lib/python3.8/site-packages/textgrid/textgr
id.py", line 807, in fromFile
    tg.read(f)
  File "/data_disk/miniconda3/envs/wenet/lib/python3.8/site-packages/textgrid/textgr
id.py", line 736, in read
    itie.addInterval(Interval(jmin, jmax, jmrk))
  File "/data_disk/miniconda3/envs/wenet/lib/python3.8/site-packages/textgrid/textgr
id.py", line 463, in addInterval
    raise ValueError(self.maxTime)
ValueError: 2104.492
```
```
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/data_disk/miniconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/dat
a/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/data_disk/miniconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/dat
a/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "tools/compute_cmvn_stats.py", line 33, in __call__
    sample_rate = torchaudio.info(
  File "/data_disk/miniconda3/envs/wenet/lib/python3.8/site-packages/torchaudio/back
end/sox_io_backend.py", line 115, in info
    return _fallback_info(filepath, format)
  File "/data_disk/miniconda3/envs/wenet/lib/python3.8/site-packages/torchaudio/back
end/sox_io_backend.py", line 14, in _fail_info
    raise RuntimeError("Failed to fetch metadata from {}".format(filepath))
RuntimeError: Failed to fetch metadata from /data_disk/datasets/AISHELL-4/train_M/wa
v/20200713_M_R002S06C01.flac.1channel.wav
```
如何解决?这是什么错误?

**Comment by xingchensong** [comment]
https://github.com/wenet-e2e/wenet/pull/2279#issuecomment-1880342576  参考这个
