### ISSUE TITLE
RuntimeError: Error loading audio file: failed to open file

### ISSUE THREAD

**Issue by turinaf** [wenet-e2e/wenet#2566]
I'm facing this issue when running stage 1 on custom dataset.
First, I thought it was about audio path issue, so I changed wav_path to absolute path, but still the error persisted. I also changed data from `.flac` format to `.wav` format, After seeing this  https://github.com/wenet-e2e/wenet/issues/2352#issuecomment-1956132744, but this also didn't solve the issue. 

stage 1: Feature Generation
using resample and new sample rate is 16000
Traceback (most recent call last):
  File "/home/turi/experiment/oasr/wenet/examples/librispeech/s0/tools/compute_cmvn_stats.py", line 122, in <module>
    for i, batch in enumerate(data_loader):
  File "/home/turi/anaconda3/envs/torch_env/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/turi/anaconda3/envs/torch_env/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/turi/anaconda3/envs/torch_env/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/home/turi/anaconda3/envs/torch_env/lib/python3.11/site-packages/torch/_utils.py", line 722, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/turi/anaconda3/envs/torch_env/lib/python3.11/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/turi/anaconda3/envs/torch_env/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/turi/experiment/oasr/wenet/examples/librispeech/s0/tools/compute_cmvn_stats.py", line 33, in __call__
    sample_rate = torchaudio.info(wav_path).sample_rate
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/turi/anaconda3/envs/torch_env/lib/python3.11/site-packages/torchaudio/_backend/utils.py", line 99, in info
    return backend.info(uri, format, buffer_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/turi/anaconda3/envs/torch_env/lib/python3.11/site-packages/torchaudio/_backend/sox.py", line 22, in info
    sinfo = sox_ext.get_info(uri, format)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/turi/anaconda3/envs/torch_env/lib/python3.11/site-packages/torch/_ops.py", line 755, in __call__
    return self._op(*args, **(kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error loading audio file: failed to open file /home/turi/experiment/oasr/data/train/sagalee_SPKRF109_130.flac

_Originally posted by @turinaf in https://github.com/wenet-e2e/wenet/issues/2352#issuecomment-2210824331_

**Comment by lsrami** [comment]
问题是否已经解决呢？你的torchaudio的版本是什么，如果torchaudio>2.0 建议conda install ffmpeg，然后使用ffmpeg bakcend

请你尝试下面代码片段是否可以成功运行
```bash
>>> audio_path='C31_597.wav'
>>> import torchaudio
>>> torchaudio.info(audio_path, backend='sox').sample_rate
16000
>>> torchaudio.info(audio_path, backend='ffmpeg').sample_rate
16000
```

**Comment by turinaf** [comment]
Thanks @lsrami 
It's solved
