### ISSUE TITLE
Null Pointer Exception in Android Demo Project

### ISSUE THREAD

**Issue by dangbo** [wenet-e2e/wenet#2620]
**Describe the bug**
Unable to build the Android demo project

**To Reproduce**
Open Android demo project in Android Studio

**Screenshots**
![4821724605013_ pic](https://github.com/user-attachments/assets/aa8dbf1c-76b7-4de2-8f25-f062e8f75276)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Version [10]

**Additional context**
```
Caused by: java.lang.NullPointerException
 at com.android.build.gradle.internal.cxx.settings.CxxAbiModelSettingsRewriterKt.calculateConfigurationHash(CxxAbiModelSettingsRewriter.kt:226)
 at com.android.build.gradle.internal.cxx.settings.CxxAbiModelSettingsRewriterKt.calculateConfigurationArguments(CxxAbiModelSettingsRewriter.kt:114)
 at com.android.build.gradle.internal.cxx.configure.CxxCreateGradleTasksKt$createInitialCxxModel$1$1$1.invoke(CxxCreateGradleTasks.kt:358)
 at com.android.build.gradle.internal.cxx.configure.CxxCreateGradleTasksKt$createInitialCxxModel$1$1$1.invoke(CxxCreateGradleTasks.kt:356)
 at com.android.build.gradle.internal.cxx.timing.TimingEnvironmentKt.time(TimingEnvironment.kt:32)
 at com.android.build.gradle.internal.cxx.configure.CxxCreateGradleTasksKt.createInitialCxxModel(CxxCreateGradleTasks.kt:356)
 at com.android.build.gradle.internal.cxx.configure.CxxCreateGradleTasksKt.createCxxVariantBuildTask(CxxCreateGradleTasks.kt:91)
 at com.android.build.gradle.internal.AbstractAppTaskManager.createCommonTasks(AbstractAppTaskManager.java:141)
 at com.android.build.gradle.internal.tasks.ApplicationTaskManager.doCreateTasksForVariant(ApplicationTaskManager.kt:85)
 at com.android.build.gradle.internal.TaskManager.createTasksForVariant(TaskManager.kt:432)
 at com.android.build.gradle.internal.TaskManager.createTasks(TaskManager.kt:327)
 at com.android.build.gradle.internal.plugins.BasePlugin.createAndroidTasks(BasePlugin.kt:693)
 at com.android.build.gradle.internal.plugins.BasePlugin$createTasks$2$1.call(BasePlugin.kt:572)
 at com.android.build.gradle.internal.profile.NoOpAnalyticsConfiguratorService.recordBlock(NoOpAnalyticsConfiguratorService.kt:53)
 at com.android.build.gradle.internal.plugins.BasePlugin$createTasks$2.accept(BasePlugin.kt:567)
 at com.android.build.gradle.internal.plugins.BasePlugin$createTasks$2.accept(BasePlugin.kt:564)
```

**Comment by sameepsharma** [comment]
Hey I'm facing same issue, were you able fix it?
