### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'r_num_blocks'

### ISSUE THREAD

**Issue by tjysdsg** [wenet-e2e/wenet#487]
**Describe the bug**
aishell2 example throws this error:

```
Traceback (most recent call last):
  File "wenet/bin/train.py", line 165, in <module>
    model = init_asr_model(configs)
  File "/mingback/students/tjy/tone_classifier/ctc_lifters/wenet/transformer/asr_model.py", line 704, in init_asr_model
    **configs['decoder_conf'])
TypeError: __init__() got an unexpected keyword argument 'r_num_blocks'
Traceback (most recent call last):
  File "wenet/bin/train.py", line 165, in <module>
    model = init_asr_model(configs)
  File "/mingback/students/tjy/tone_classifier/ctc_lifters/wenet/transformer/asr_model.py", line 704, in init_asr_model
    **configs['decoder_conf'])
TypeError: __init__() got an unexpected keyword argument 'r_num_blocks'
```

The reason is that in `train_unified_transformer.yaml`, the `decoder_conf` contains this line:
```
  r_num_blocks: 3
```
while `TransformerDecoder.__init__()` does not have an argument called `r_num_blocks`
```python
class TransformerDecoder(torch.nn.Module):
    def __init__(
        self,
        vocab_size: int,
        encoder_output_size: int,
        attention_heads: int = 4,
        linear_units: int = 2048,
        num_blocks: int = 6,
        dropout_rate: float = 0.1,
        positional_dropout_rate: float = 0.1,
        self_attention_dropout_rate: float = 0.0,
        src_attention_dropout_rate: float = 0.0,
        input_layer: str = "embed",
        use_output_layer: bool = True,
        normalize_before: bool = True,
        concat_after: bool = False,
    ):
```

**To Reproduce**

Run the aishell2 example

**Comment by tjysdsg** [comment]
I can make a PR to remove the `r_num_blocks` key if that's the way to solve this issue?

**Comment by robin1001** [comment]
Sorry for the late reply. Yes, it's the right way to fix the bug.
