### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by mirishkarganesh** [wenet-e2e/wenet#503]
Hi Folks,

I have used default librispeech recipe on my own database. At stage 4 I have encounter the below can someone help me in solving the above issue.  
```bash
(ctc): CTC(
    (ctc_lo): Linear(in_features=512, out_features=5058, bias=True)
    (ctc_loss): CTCLoss()
  )
  (criterion_att): LabelSmoothingLoss(
    (criterion): KLDivLoss()
  )
)2021-07-08 12:28:17,337 INFO Epoch 0 TRAIN info lr 8e-08
2021-07-08 12:28:17,337 INFO Epoch 0 TRAIN info lr 8e-08
2021-07-08 12:28:17,338 INFO Checkpoint: save to checkpoint exp/sp_spec_aug/init.pt
2021-07-08 12:28:17,338 INFO Epoch 0 TRAIN info lr 8e-08
2021-07-08 12:28:17,338 INFO using accumulate grad, new batch size is 4 timeslarger than before
2021-07-08 12:28:17,339 INFO using accumulate grad, new batch size is 4 timeslarger than before
2021-07-08 12:28:17,339 INFO Epoch 0 TRAIN info lr 8e-08
2021-07-08 12:28:17,339 INFO Epoch 0 TRAIN info lr 8e-08
2021-07-08 12:28:17,339 INFO using accumulate grad, new batch size is 4 timeslarger than before
2021-07-08 12:28:17,340 INFO using accumulate grad, new batch size is 4 timeslarger than before

the number of model params: 129093508

the number of model params: 129093508
2021-07-08 12:28:17,340 INFO using accumulate grad, new batch size is 4 timeslarger than before

the number of model params: 129093508

the number of model params: 129093508

the number of model params: 129093508
Traceback (most recent call last):
  File "wenet/bin/train.py", line 228, in <module>
    executor.train(model, optimizer, scheduler, train_data_loader, device,
  File "/2expasr/ganesh/new_exps/asr/e2e/wenet_exp/eng_iitm/wenet/utils/executor.py", line 33, in train
    for batch_idx, batch in enumerate(data_loader):
  File "/home/asr/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 291, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/home/asr/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 764, in __init__
    self._try_put_index()
  File "/home/asr/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 994, in _try_put_index
    index = self._next_index()
  File "/home/asr/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 357, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/asr/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 208, in __iter__
    for idx in self.sampler:
  File "/home/asr/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/distributed.py", line 80, in __iter__
    assert len(indices) == self.total_size
AssertionError
Traceback (most recent call last):
  File "wenet/bin/train.py", line 228, in <module>
    executor.train(model, optimizer, scheduler, train_data_loader, device,
  File "/2expasr/ganesh/new_exps/asr/e2e/wenet_exp/eng_iitm/wenet/utils/executor.py", line 33, in train
    for batch_idx, batch in enumerate(data_loader):
  File "/home/asr/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 291, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/home/asr/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 764, in __init__
    self._try_put_index()
  File "/home/asr/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 994, in _try_put_index
    index = self._next_index()
  File "/home/asr/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 357, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/asr/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 208, in __iter__
    for idx in self.sampler:
  File "/home/asr/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/distributed.py", line 80, in __iter__
    assert len(indices) == self.total_size
AssertionError
Traceback (most recent call last):
  File "wenet/bin/train.py", line 228, in <module>
    executor.train(model, optimizer, scheduler, train_data_loader, device,
  File "/2expasr/ganesh/new_exps/asr/e2e/wenet_exp/eng_iitm/wenet/utils/executor.py", line 33, in train
    for batch_idx, batch in enumerate(data_loader):
  File "/home/asr/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 291, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/home/asr/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 764, in __init__
    self._try_put_index()
  File "/home/asr/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 994, in _try_put_index
    index = self._next_index()
  File "/home/asr/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 357, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/asr/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 208, in __iter__
    for idx in self.sampler:
  File "/home/asr/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/distributed.py", line 80, in __iter__
    assert len(indices) == self.total_size
AssertionError
Traceback (most recent call last):
  File "wenet/bin/train.py", line 228, in <module>
    executor.train(model, optimizer, scheduler, train_data_loader, device,
  File "/2expasr/ganesh/new_exps/asr/e2e/wenet_exp/eng_iitm/wenet/utils/executor.py", line 33, in train
    for batch_idx, batch in enumerate(data_loader):
  File "/home/asr/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 291, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/home/asr/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 764, in __init__
    self._try_put_index()
  File "/home/asr/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 994, in _try_put_index
    index = self._next_index()
  File "/home/asr/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 357, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/asr/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 208, in __iter__
    for idx in self.sampler:
  File "/home/asr/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/distributed.py", line 80, in __iter__
    assert len(indices) == self.total_size
AssertionError
Traceback (most recent call last):
  File "wenet/bin/train.py", line 228, in <module>
    executor.train(model, optimizer, scheduler, train_data_loader, device,
  File "/2expasr/ganesh/new_exps/asr/e2e/wenet_exp/eng_iitm/wenet/utils/executor.py", line 33, in train
    for batch_idx, batch in enumerate(data_loader):
  File "/home/asr/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 291, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/home/asr/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 764, in __init__
    self._try_put_index()
  File "/home/asr/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 994, in _try_put_index
    index = self._next_index()
  File "/home/asr/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 357, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/asr/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 208, in __iter__
    for idx in self.sampler:
  File "/home/asr/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/distributed.py", line 80, in __iter__
    assert len(indices) == self.total_size
AssertionError
2021-07-08 12:28:18,178 INFO Epoch 0 TRAIN info lr 8e-08
2021-07-08 12:28:18,179 INFO using accumulate grad, new batch size is 4 timeslarger than before

the number of model params: 129093508
Traceback (most recent call last):
  File "wenet/bin/train.py", line 228, in <module>
    executor.train(model, optimizer, scheduler, train_data_loader, device,
  File "/2expasr/ganesh/new_exps/asr/e2e/wenet_exp/eng_iitm/wenet/utils/executor.py", line 33, in train
    for batch_idx, batch in enumerate(data_loader):
  File "/home/asr/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 291, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/home/asr/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 764, in __init__
    self._try_put_index()
  File "/home/asr/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 994, in _try_put_index
    index = self._next_index()
  File "/home/asr/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 357, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/home/asr/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 208, in __iter__
    for idx in self.sampler:
  File "/home/asr/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/distributed.py", line 80, in __iter__
    assert len(indices) == self.total_size
AssertionError
do model average and final checkpoint is exp/sp_spec_aug/avg_20.pt
Namespace(dst_model='exp/sp_spec_aug/avg_20.pt', max_epoch=65536, min_epoch=0, num=20, src_path='exp/sp_spec_aug', val_best=True)
Traceback (most recent call last):
  File "wenet/bin/average_model.py", line 47, in <module>
    sort_idx = np.argsort(val_scores[:, -1])
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

**Comment by robin1001** [comment]
Maybe you have some problems(wrong setting) with distributed parallel training, please first try single GPU training.

**Comment by robin1001** [comment]
Maybe you have some problems(wrong setting) with distributed parallel training, please first try single GPU training.

**Comment by MomentOfTime** [comment]
i also have same problem. after seeing your advice, i realize just one gpu card in pc. updating the call `export CUDA_VISIBLE_DEVICES="0"` in run.sh  can help solve the problem. 
but another problem happens as follow:
`
2022-02-25 18:50:48,044 DEBUG TRAIN Batch 0/0 loss 183.073685 loss_att 68.438400 loss_ctc 450.556030 lr 0.00000008 rank 0
Traceback (most recent call last):
  File "wenet/bin/train.py", line 278, in <module>
    main()
  File "wenet/bin/train.py", line 251, in main
    executor.train(model, optimizer, scheduler, train_data_loader, device,
  File "/mnt/g/wenet_location/wenet/wenet/utils/executor.py", line 71, in train
    loss.backward()
  File "/home/lyl/miniconda3/envs/wenet/lib/python3.8/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/lyl/miniconda3/envs/wenet/lib/python3.8/site-packages/torch/autograd/__init__.py", line 154, in backward
    Variable._execution_engine.run_backward(
RuntimeError: CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
`
in  stage 4 of the example of aishell/s0.
