### ISSUE TITLE
compute_cmvn_stats.py error

### ISSUE THREAD

**Issue by garymmi** [wenet-e2e/wenet#818]
when run tools/compute_cmvn_stats.py, error as below

processed 105000 wavs, 50282789 frames
processed 106000 wavs, 50759224 frames
processed 107000 wavs, 51244186 frames
processed 108000 wavs, 51719825 frames
processed 109000 wavs, 52208996 frames
processed 110000 wavs, 52689996 frames
processed 111000 wavs, 53177230 frames
processed 112000 wavs, 53642001 frames
Traceback (most recent call last):
  File "tools/compute_cmvn_stats.py", line 122, in <module>
    for i, batch in enumerate(data_loader):
  File "/nick/miniconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/nick/miniconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1183, in _next_data
    return self._process_data(data)
  File "/nick/miniconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/nick/miniconda3/envs/wenet/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
AssertionError: Caught AssertionError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "/nick/miniconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/nick/miniconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "tools/compute_cmvn_stats.py", line 55, in __call__
    mat = kaldi.fbank(waveform,
  File "/nick/miniconda3/envs/wenet/lib/python3.8/site-packages/torchaudio/compliance/kaldi.py", line 561, in fbank
    waveform, window_shift, window_size, padded_window_size = _get_waveform_and_window_properties(
  File "/nick/miniconda3/envs/wenet/lib/python3.8/site-packages/torchaudio/compliance/kaldi.py", line 144, in **_get_waveform_and_window_properties
    assert 2 <= window_size <= len(
AssertionError: choose a window size 200 that is [2, 0]**

how to fix it ?
or how to verify training data is ok ?

thanks

**Comment by garymmi** [comment]
some files are empty, close issue
