### ISSUE TITLE
Use DDP training to get stuck

### ISSUE THREAD

**Issue by 601222543** [wenet-e2e/wenet#842]
## Describe the bug
I got stuck when using DDP training with my own wenet and my own data. And stuck(GPU utilization 100%) at the beginning of the second epoch every time.
After debugging, it was found to be stuck in this position:
```
# wenet/utils/executor.py
with torch.cuda.amp.autocast(scaler is not None):
    loss, loss_att, loss_ctc = model(
        feats, feats_lengths, target, target_lengths)
```

## Environment
CentOS Linux release 7.8.2003 (Core)
GPU Driver Version: 450.80.02
CUDA Version: 10.2
torch==1.8.0
torchaudio==1.8.1
torchvision==0.9.0

## Some Attempts
I did some attempts later and found:
1 gpu no problem
multi gpu stuck
`static batch` no problem
`dynamic batch` stuck
`conformer` no problem
`unified_conformer` stuck

Other attempts：
Upgrade pytorch version to 1.9.0, 1.10.0 is useless
Set num_workers=0/1 is useless
V100 -> P40 useless
Sleep 1 minute after completing an epoch is useless
NCCL is completely stuck without error log
GLOO error log:
```
2021-12-07 11:36:17,011 INFO Epoch 0 CV info cv_loss 115.3632936241356
2021-12-07 11:36:17,011 INFO Epoch 1 TRAIN info lr 6.08e-06
2021-12-07 11:36:17,014 INFO using accumulate grad, new batch size is 8 times larger than before
2021-12-07 11:36:17,335 INFO Epoch 0 CV info cv_loss 115.36239801458647
2021-12-07 11:36:17,335 INFO Epoch 1 TRAIN info lr 6.200000000000001e-06
2021-12-07 11:36:17,338 INFO using accumulate grad, new batch size is 8 times larger than before
2021-12-07 11:36:17,579 INFO Epoch 0 CV info cv_loss 115.36309641650827
2021-12-07 11:36:17,579 INFO Epoch 1 TRAIN info lr 5.96e-06
2021-12-07 11:36:17,582 INFO using accumulate grad, new batch size is 8 times larger than before
2021-12-07 11:36:17,926 INFO Epoch 0 CV info cv_loss 115.36275817930736
2021-12-07 11:36:17,926 INFO Checkpoint: save to checkpoint exp/conformer/0.pt
2021-12-07 11:36:18,889 INFO Epoch 1 TRAIN info lr 6.32e-06
2021-12-07 11:36:18,892 INFO using accumulate grad, new batch size is 8 times larger than before
terminate called after throwing an instance of 'gloo::EnforceNotMet'
  what():  [enforce fail at /opt/conda/conda-bld/pytorch_1614378062065/work/third_party/gloo/gloo/transport/tcp/pair.cc:490] op.preamble.length <= op.nbytes. 939336 vs 4
./run.sh: line 165:  7108 Aborted                 (core dumped) python wenet/bin/train.py --gpu $gpu_id --config $train_config --data_type $data_type --symbol_table $dict --train_data data/$train_set/data.list --cv_data data/dev/data.list ${checkpoint:+--checkpoint $checkpoint} --model_dir $dir --ddp.init_method $init_method --ddp.world_size $world_size --ddp.rank $rank --ddp.dist_backend $dist_backend --num_workers 8 $cmvn_opts --pin_memory
/homepath/envs/anaconda3/lib/python3.8/multiprocessing/process.py:108: ResourceWarning: unclosed file <_io.BufferedReader name='/homepath/tools/wenet-uio/examples/aishell/s0/data/train/shards/shards_000000002.tar'>
  self._target(*self._args, **self._kwargs)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/homepath/envs/anaconda3/lib/python3.8/multiprocessing/process.py:108: ResourceWarning: unclosed file <_io.BufferedReader name='/homepath/tools/wenet-uio/examples/aishell/s0/data/train/shards/shards_000000110.tar'>
  self._target(*self._args, **self._kwargs)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/homepath/envs/anaconda3/lib/python3.8/multiprocessing/process.py:108: ResourceWarning: unclosed file <_io.BufferedReader name='/homepath/tools/wenet-uio/examples/aishell/s0/data/train/shards/shards_000000112.tar'>
  self._target(*self._args, **self._kwargs)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/homepath/envs/anaconda3/lib/python3.8/multiprocessing/process.py:108: ResourceWarning: unclosed file <_io.BufferedReader name='/homepath/tools/wenet-uio/examples/aishell/s0/data/train/shards/shards_000000075.tar'>
  self._target(*self._args, **self._kwargs)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/homepath/envs/anaconda3/lib/python3.8/multiprocessing/process.py:108: ResourceWarning: unclosed file <_io.BufferedReader name='/homepath/tools/wenet-uio/examples/aishell/s0/data/train/shards/shards_000000001.tar'>
  self._target(*self._args, **self._kwargs)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/homepath/envs/anaconda3/lib/python3.8/multiprocessing/process.py:108: ResourceWarning: unclosed file <_io.BufferedReader name='/homepath/tools/wenet-uio/examples/aishell/s0/data/train/shards/shards_000000086.tar'>
  self._target(*self._args, **self._kwargs)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "wenet/bin/train.py", line 277, in <module>
    main()
  File "wenet/bin/train.py", line 250, in main
    executor.train(model, optimizer, scheduler, train_data_loader, device,
  File "/homepath/tools/wenet-uio/wenet/utils/executor.py", line 71, in train
    loss.backward()
  File "/homepath/envs/anaconda3/lib/python3.8/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/homepath/envs/anaconda3/lib/python3.8/site-packages/torch/autograd/__init__.py", line 145, in backward
    Variable._execution_engine.run_backward(
RuntimeError: [/opt/conda/conda-bld/pytorch_1614378062065/work/third_party/gloo/gloo/transport/tcp/pair.cc:575] Connection closed by peer [11.88.165.7]:54008
Traceback (most recent call last):
  File "wenet/bin/train.py", line 277, in <module>
    main()
  File "wenet/bin/train.py", line 250, in main
    executor.train(model, optimizer, scheduler, train_data_loader, device,
  File "/homepath/tools/wenet-uio/wenet/utils/executor.py", line 71, in train
    loss.backward()
  File "/homepath/envs/anaconda3/lib/python3.8/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/homepath/envs/anaconda3/lib/python3.8/site-packages/torch/autograd/__init__.py", line 145, in backward
    Variable._execution_engine.run_backward(
RuntimeError: Application timeout caused pair closure
```

## To Reproduce
Finally, pull the latest wenet code，reproduced the above problem with aishell recipe:
```
data_type=shard
train_config=conf/train_unified_conformer.yaml
cmvn=false
dynamic batch
accum_grad=8
```
　　
How should this be solved? Thank you.

**Comment by robin1001** [comment]
I have no idea, do you get it fixed?

**Comment by 601222543** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by 601222543** [comment]
Not yet, try to replace DDP? 

https://github.com/pytorch/pytorch/issues/13273
https://github.com/NVIDIA/apex

**Comment by chiendb97** [comment]
@601222543 I also got the same error after pulling the latest wenet code. Have you solved this problem yet?

**Comment by kobenaxie** [comment]
@601222543 thanks, I find only need to modify the code in `cv(self, model, data_loader, device, args)`, it will be solved.

**Comment by 601222543** [comment]
@kobenaxie Yes, you are right.

**Comment by chiendb97** [comment]
> 

@kobenaxie can you share your code? thank you

**Comment by zelda3721** [comment]
> @601222543 thanks, I find only need to modify the code in `cv(self, model, data_loader, device, args)`, it will be solved.



> > 
> 
> @kobenaxie can you share your code? thank you

same issue, can you share your code? thank you!

**Comment by 601222543** [comment]
dynamic batch for `train` static batch for `cv` can also solve this problem.

**Comment by kobenaxie** [comment]
Just modify executor.py as @601222543 mentioned, @zelda3721 @chiendb97 , hopes it is useful.
```
# Copyright 2019 Mobvoi Inc. All Rights Reserved.
# Author: binbinzhang@mobvoi.com (Binbin Zhang)

import logging
from contextlib import nullcontext
# if your python version < 3.7 use the below one
# from contextlib import suppress as nullcontext
import torch
from torch.nn.utils import clip_grad_norm_
from torch.distributed import ReduceOp

class Executor:
    def __init__(self):
        self.step = 0

    def train(self, model, optimizer, scheduler, data_loader, device, writer,
              args, scaler):
        ''' Train one epoch
        '''
        model.train()
        clip = args.get('grad_clip', 50.0)
        log_interval = args.get('log_interval', 10)
        rank = args.get('rank', 0)
        epoch = args.get('epoch', 0)
        accum_grad = args.get('accum_grad', 1)
        is_distributed = args.get('is_distributed', True)
        use_amp = args.get('use_amp', False)
        logging.info('using accumulate grad, new batch size is {} times'
                     ' larger than before'.format(accum_grad))
        if use_amp:
            assert scaler is not None
        # A context manager to be used in conjunction with an instance of
        # torch.nn.parallel.DistributedDataParallel to be able to train
        # with uneven inputs across participating processes.
        if isinstance(model, torch.nn.parallel.DistributedDataParallel):
            model_context = model.join
        else:
            model_context = nullcontext
        num_seen_utts = 0
        with model_context():
            for batch_idx, batch in enumerate(data_loader):
                key, feats, target, feats_lengths, target_lengths = batch
                feats = feats.to(device)
                target = target.to(device)
                feats_lengths = feats_lengths.to(device)
                target_lengths = target_lengths.to(device)
                num_utts = target_lengths.size(0)
                if num_utts == 0:
                    continue
                context = None
                # Disable gradient synchronizations across DDP processes.
                # Within this context, gradients will be accumulated on module
                # variables, which will later be synchronized.
                if is_distributed and batch_idx % accum_grad != 0:
                    context = model.no_sync
                # Used for single gpu training and DDP gradient synchronization
                # processes.
                else:
                    context = nullcontext
                with context():
                    # autocast context
                    # The more details about amp can be found in
                    # https://pytorch.org/docs/stable/notes/amp_examples.html
                    with torch.cuda.amp.autocast(scaler is not None):
                        loss, loss_att, loss_ctc = model(
                            feats, feats_lengths, target, target_lengths)
                        loss = loss / accum_grad
                    if use_amp:
                        scaler.scale(loss).backward()
                    else:
                        loss.backward()

                num_seen_utts += num_utts
                if batch_idx % accum_grad == 0:
                    if rank == 0 and writer is not None:
                        writer.add_scalar('train_loss', loss, self.step)
                    # Use mixed precision training
                    if use_amp:
                        scaler.unscale_(optimizer)
                        grad_norm = clip_grad_norm_(model.parameters(), clip)
                        # Must invoke scaler.update() if unscale_() is used in
                        # the iteration to avoid the following error:
                        #   RuntimeError: unscale_() has already been called
                        #   on this optimizer since the last update().
                        # We don't check grad here since that if the gradient
                        # has inf/nan values, scaler.step will skip
                        # optimizer.step().
                        scaler.step(optimizer)
                        scaler.update()
                    else:
                        grad_norm = clip_grad_norm_(model.parameters(), clip)
                        if torch.isfinite(grad_norm):
                            optimizer.step()
                    optimizer.zero_grad()
                    scheduler.step()
                    self.step += 1
                if batch_idx % log_interval == 0:
                    lr = optimizer.param_groups[0]['lr']
                    log_str = 'TRAIN Batch {}/{} loss {:.6f} '.format(
                        epoch, batch_idx,
                        loss.item() * accum_grad)
                    if loss_att is not None:
                        log_str += 'loss_att {:.6f} '.format(loss_att.item())
                    if loss_ctc is not None:
                        log_str += 'loss_ctc {:.6f} '.format(loss_ctc.item())
                    log_str += 'lr {:.8f} rank {}'.format(lr, rank)
                    logging.debug(log_str)

    def cv(self, model, data_loader, device, args):
        ''' Cross validation on
        '''
        model.eval()
        rank = args.get('rank', 0)
        epoch = args.get('epoch', 0)
        log_interval = args.get('log_interval', 10)
        is_distributed = args.get('is_distributed', True)
        # in order to avoid division by 0
        num_seen_utts = 1
        total_loss = 0.0
        with torch.no_grad():
            iterator_stop = torch.tensor(0).to("cuda")
            for batch_idx, batch in enumerate(data_loader):
                if is_distributed:
                    torch.distributed.all_reduce(iterator_stop, ReduceOp.SUM)
                    if iterator_stop > 0:
                        break
                key, feats, target, feats_lengths, target_lengths = batch
                feats = feats.to(device)
                target = target.to(device)
                feats_lengths = feats_lengths.to(device)
                target_lengths = target_lengths.to(device)
                num_utts = target_lengths.size(0)
                if num_utts == 0:
                    continue
                loss, loss_att, loss_ctc = model(feats, feats_lengths, target,
                                                 target_lengths)
                if torch.isfinite(loss):
                    num_seen_utts += num_utts
                    total_loss += loss.item() * num_utts
                if batch_idx % log_interval == 0:
                    log_str = 'CV Batch {}/{} loss {:.6f} '.format(
                        epoch, batch_idx, loss.item())
                    if loss_att is not None:
                        log_str += 'loss_att {:.6f} '.format(loss_att.item())
                    if loss_ctc is not None:
                        log_str += 'loss_ctc {:.6f} '.format(loss_ctc.item())
                    log_str += 'history loss {:.6f}'.format(total_loss /
                                                            num_seen_utts)
                    log_str += ' rank {}'.format(rank)
                    logging.debug(log_str)
            else:
                if is_distributed:
                    iterator_stop.fill_(1)
                    torch.distributed.all_reduce(iterator_stop, ReduceOp.SUM)
        return total_loss, num_seen_utts

```

**Comment by robin1001** [comment]
Fixed, please see https://github.com/wenet-e2e/wenet/pull/903/
