### ISSUE TITLE
直接对model.half()输出的fp16的pytorch模型无法正常使用

### ISSUE THREAD

**Issue by piekey1994** [wenet-e2e/wenet#913]
**Describe the bug**
想尝试在gpu上使用fp16的pytorch模型做推理，尝试直接对模型做half操作在推理的时候会报错。请问有什么好的方法导出fp16的pytorch模型吗
```
Traceback (most recent call last):
  File "wenet/bin/export_jit_encoder.py", line 117, in <module>
    encoder(feats,feats_lengths)
  File "/data/wenet/torch181/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "wenet/bin/export_jit_encoder.py", line 52, in forward
    encoder_out, encoder_mask = self.encoder(speech,
  File "/data/wenet/torch181/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "./wenet/transformer/encoder.py", line 163, in forward
    xs, chunk_masks, _ = layer(xs, chunk_masks, pos_emb, mask_pad)
  File "/data/wenet/torch181/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "./wenet/transformer/encoder_layer.py", line 231, in forward
    x_att = self.self_attn(x_q, x, x, mask, pos_emb)
  File "/data/wenet/torch181/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "./wenet/transformer/attention.py", line 198, in forward
    p = self.linear_pos(pos_emb).view(n_batch_pos, -1, self.h, self.d_k)
  File "/data/wenet/torch181/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data/wenet/torch181/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 94, in forward
    return F.linear(input, self.weight, self.bias)
  File "/data/wenet/torch181/lib/python3.8/site-packages/torch/nn/functional.py", line 1753, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: expected scalar type Float but found Half
```

**Comment by Slyne** [comment]
你的输入有变成fp16吗？
```
if args.fp16:
    if input.dtype == torch.float32:
        input= input.half()
```

另外如果fp16 pytorch推理遇到NAN问题可以拉一下最新的代码

**Comment by piekey1994** [comment]
> 你的输入有变成fp16吗？
> 
> ```
> if args.fp16:
>     if input.dtype == torch.float32:
>         input= input.half()
> ```
> 
> 另外如果fp16 pytorch推理遇到NAN问题可以拉一下最新的代码

我的输入也half了，model也half了，还是会报这个错误，nan的问题在fp16的onnx有遇到，pytorch的fp16不知道怎么搞

**Comment by Slyne** [comment]
在[这行](https://github.com/wenet-e2e/wenet/blob/main/wenet/transformer/encoder.py#L154)前加一句:
```
pos_emb = pos_emb.to(xs.dtype)
```
把position embedding转成fp16

**Comment by piekey1994** [comment]
> 在[这行](https://github.com/wenet-e2e/wenet/blob/main/wenet/transformer/encoder.py#L154)前加一句:
> 
> ```
> pos_emb = pos_emb.to(xs.dtype)
> ```
> 
> 把position embedding转成fp16

成功了，谢谢，速度几乎翻倍，字错率差别不大，牛!
