### ISSUE TITLE
flock: Transport endpoint is not connected

### ISSUE THREAD

**Issue by srdfjy** [wenet-e2e/wenet#976]
Hi，The following error occurs while using ddp.
2022/03/12 16:42:35 what(): flock: Transport endpoint is not connected

but It is successful when I use 2 and 4 machine nodes.

env
---
num_nodes=6
dist_backend="nccl"
init method=file:///data/exp/u2++_conformer/ddp_init

One gpu card per machine
Using shared storage glusterfs, not using nfs

err
---
2022/03/12 13:36:31 run.sh: init method is file:///data/exp/u2++_conformer/ddp_init
2022/03/12 13:42:34 2022-03-12 13:42:34,223 INFO training on multiple gpus, this gpu 0
2022/03/12 13:42:34 2022-03-12 13:42:34,267 INFO Added key: store_based_barrier_key:1 to store for rank: 1
2022/03/12 15:12:35 Traceback (most recent call last):
2022/03/12 15:12:35   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py", line 525, in init_process_group
2022/03/12 15:12:35     worker_count = store.add(store_key, 0)
2022/03/12 15:12:35   File "wenet/bin/train.py", line 119, in <module>
2022/03/12 15:12:35 RuntimeError: flock: Transport endpoint is not connected
2022/03/12 15:12:35     _store_based_barrier(rank, store, timeout)
2022/03/12 15:12:35 Namespace(checkpoint=None, cmvn='/data/exp/u2++_conformer/global_cmvn', config='conf/train_u2++_conformer.yaml', cv_data='/data/exp/u2++_conformer/dev.format.data', dist_backend='nccl', gpu=0, init_method='file:///data/exp/u2++_conformer/ddp_init', model_dir='/data/exp/u2++_conformer', num_workers=2, pin_memory=True, rank=1, tensorboard_dir='tensorboard', train_data='/data/exp/u2++_conformer/train.format.data', use_amp=False, world_size=8)
2022/03/12 15:12:35     dist.init_process_group(args.dist_backend,
2022/03/12 15:12:35   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/distributed_c10d.py", line 201, in _store_based_barrier
2022/03/12 16:42:35   what():  flock: Transport endpoint is not connected
2022/03/12 16:42:35 terminate called after throwing an instance of 'std::system_error'
2022/03/12 16:42:35 run.sh: line 178:   730 Aborted                 (core dumped) python wenet/bin/train.py --gpu $gpu_id --config $train_config --train_data $dir/train.format.data --cv_data $dir/dev.format.data ${checkpoint:+--checkpoint $checkpoint} --model_dir $dir --ddp.init_method $init_method --ddp.world_size $world_size --ddp.rank $rank --ddp.dist_backend $dist_backend --num_workers 2 $cmvn_opts --pin_memory
2022/03/12 16:42:35 exec result:0

**Comment by srdfjy** [comment]
I fixed the problem temporarily by modifying init_method for tcp.
